// Husky UGV Extension Protocol
//
// Extension telemetry and command definitions for Clearpath Husky A200 UGV.
// This is an extension proto — payloads are carried inside pidgin.ExtensionData.
//
// See docs/EXTENSIBILITY.md for extension architecture.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/extensions/husky/husky.proto

package husky

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DriveMode represents the vehicle's current control mode.
type DriveMode int32

const (
	DriveMode_DRIVE_MODE_UNKNOWN    DriveMode = 0
	DriveMode_DRIVE_MODE_MANUAL     DriveMode = 1 // Direct teleop control
	DriveMode_DRIVE_MODE_AUTONOMOUS DriveMode = 2 // Self-driving to waypoints
	DriveMode_DRIVE_MODE_GUIDED     DriveMode = 3 // External guidance (ROS nav stack)
)

// Enum value maps for DriveMode.
var (
	DriveMode_name = map[int32]string{
		0: "DRIVE_MODE_UNKNOWN",
		1: "DRIVE_MODE_MANUAL",
		2: "DRIVE_MODE_AUTONOMOUS",
		3: "DRIVE_MODE_GUIDED",
	}
	DriveMode_value = map[string]int32{
		"DRIVE_MODE_UNKNOWN":    0,
		"DRIVE_MODE_MANUAL":     1,
		"DRIVE_MODE_AUTONOMOUS": 2,
		"DRIVE_MODE_GUIDED":     3,
	}
)

func (x DriveMode) Enum() *DriveMode {
	p := new(DriveMode)
	*p = x
	return p
}

func (x DriveMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriveMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_extensions_husky_husky_proto_enumTypes[0].Descriptor()
}

func (DriveMode) Type() protoreflect.EnumType {
	return &file_internal_extensions_husky_husky_proto_enumTypes[0]
}

func (x DriveMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriveMode.Descriptor instead.
func (DriveMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_extensions_husky_husky_proto_rawDescGZIP(), []int{0}
}

// HuskyTelemetry contains Husky-specific state sent in VehicleTelemetry.extensions["husky"].
type HuskyTelemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current drive mode
	DriveMode DriveMode `protobuf:"varint,1,opt,name=drive_mode,json=driveMode,proto3,enum=husky.DriveMode" json:"drive_mode,omitempty"`
	// Battery voltage in volts (typically 24-30V for Husky)
	BatteryVoltage float32 `protobuf:"fixed32,2,opt,name=battery_voltage,json=batteryVoltage,proto3" json:"battery_voltage,omitempty"`
	// Bumper contact states
	BumperContacts *BumperContacts `protobuf:"bytes,3,opt,name=bumper_contacts,json=bumperContacts,proto3" json:"bumper_contacts,omitempty"`
	// Motor temperatures in Celsius (left, right)
	MotorTempLeftC  float32 `protobuf:"fixed32,4,opt,name=motor_temp_left_c,json=motorTempLeftC,proto3" json:"motor_temp_left_c,omitempty"`
	MotorTempRightC float32 `protobuf:"fixed32,5,opt,name=motor_temp_right_c,json=motorTempRightC,proto3" json:"motor_temp_right_c,omitempty"`
	// Wheel odometry in meters since boot
	OdometryLeftM  float32 `protobuf:"fixed32,6,opt,name=odometry_left_m,json=odometryLeftM,proto3" json:"odometry_left_m,omitempty"`
	OdometryRightM float32 `protobuf:"fixed32,7,opt,name=odometry_right_m,json=odometryRightM,proto3" json:"odometry_right_m,omitempty"`
	// E-Stop engaged (hardware or software)
	EstopEngaged  bool `protobuf:"varint,8,opt,name=estop_engaged,json=estopEngaged,proto3" json:"estop_engaged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HuskyTelemetry) Reset() {
	*x = HuskyTelemetry{}
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HuskyTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuskyTelemetry) ProtoMessage() {}

func (x *HuskyTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuskyTelemetry.ProtoReflect.Descriptor instead.
func (*HuskyTelemetry) Descriptor() ([]byte, []int) {
	return file_internal_extensions_husky_husky_proto_rawDescGZIP(), []int{0}
}

func (x *HuskyTelemetry) GetDriveMode() DriveMode {
	if x != nil {
		return x.DriveMode
	}
	return DriveMode_DRIVE_MODE_UNKNOWN
}

func (x *HuskyTelemetry) GetBatteryVoltage() float32 {
	if x != nil {
		return x.BatteryVoltage
	}
	return 0
}

func (x *HuskyTelemetry) GetBumperContacts() *BumperContacts {
	if x != nil {
		return x.BumperContacts
	}
	return nil
}

func (x *HuskyTelemetry) GetMotorTempLeftC() float32 {
	if x != nil {
		return x.MotorTempLeftC
	}
	return 0
}

func (x *HuskyTelemetry) GetMotorTempRightC() float32 {
	if x != nil {
		return x.MotorTempRightC
	}
	return 0
}

func (x *HuskyTelemetry) GetOdometryLeftM() float32 {
	if x != nil {
		return x.OdometryLeftM
	}
	return 0
}

func (x *HuskyTelemetry) GetOdometryRightM() float32 {
	if x != nil {
		return x.OdometryRightM
	}
	return 0
}

func (x *HuskyTelemetry) GetEstopEngaged() bool {
	if x != nil {
		return x.EstopEngaged
	}
	return false
}

// BumperContacts reports physical contact on each bumper.
type BumperContacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrontLeft     bool                   `protobuf:"varint,1,opt,name=front_left,json=frontLeft,proto3" json:"front_left,omitempty"`
	FrontRight    bool                   `protobuf:"varint,2,opt,name=front_right,json=frontRight,proto3" json:"front_right,omitempty"`
	RearLeft      bool                   `protobuf:"varint,3,opt,name=rear_left,json=rearLeft,proto3" json:"rear_left,omitempty"`
	RearRight     bool                   `protobuf:"varint,4,opt,name=rear_right,json=rearRight,proto3" json:"rear_right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BumperContacts) Reset() {
	*x = BumperContacts{}
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BumperContacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumperContacts) ProtoMessage() {}

func (x *BumperContacts) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumperContacts.ProtoReflect.Descriptor instead.
func (*BumperContacts) Descriptor() ([]byte, []int) {
	return file_internal_extensions_husky_husky_proto_rawDescGZIP(), []int{1}
}

func (x *BumperContacts) GetFrontLeft() bool {
	if x != nil {
		return x.FrontLeft
	}
	return false
}

func (x *BumperContacts) GetFrontRight() bool {
	if x != nil {
		return x.FrontRight
	}
	return false
}

func (x *BumperContacts) GetRearLeft() bool {
	if x != nil {
		return x.RearLeft
	}
	return false
}

func (x *BumperContacts) GetRearRight() bool {
	if x != nil {
		return x.RearRight
	}
	return false
}

// SetDriveModeCommand changes the drive mode.
type SetDriveModeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          DriveMode              `protobuf:"varint,1,opt,name=mode,proto3,enum=husky.DriveMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDriveModeCommand) Reset() {
	*x = SetDriveModeCommand{}
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDriveModeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDriveModeCommand) ProtoMessage() {}

func (x *SetDriveModeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDriveModeCommand.ProtoReflect.Descriptor instead.
func (*SetDriveModeCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_husky_husky_proto_rawDescGZIP(), []int{2}
}

func (x *SetDriveModeCommand) GetMode() DriveMode {
	if x != nil {
		return x.Mode
	}
	return DriveMode_DRIVE_MODE_UNKNOWN
}

// SetBumperSensitivityCommand adjusts collision detection threshold.
type SetBumperSensitivityCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sensitivity level 0-100 (0 = disabled, 100 = most sensitive)
	Sensitivity   uint32 `protobuf:"varint,1,opt,name=sensitivity,proto3" json:"sensitivity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBumperSensitivityCommand) Reset() {
	*x = SetBumperSensitivityCommand{}
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBumperSensitivityCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBumperSensitivityCommand) ProtoMessage() {}

func (x *SetBumperSensitivityCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBumperSensitivityCommand.ProtoReflect.Descriptor instead.
func (*SetBumperSensitivityCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_husky_husky_proto_rawDescGZIP(), []int{3}
}

func (x *SetBumperSensitivityCommand) GetSensitivity() uint32 {
	if x != nil {
		return x.Sensitivity
	}
	return 0
}

// TriggerEStopCommand engages the software E-Stop.
type TriggerEStopCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEStopCommand) Reset() {
	*x = TriggerEStopCommand{}
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEStopCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEStopCommand) ProtoMessage() {}

func (x *TriggerEStopCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEStopCommand.ProtoReflect.Descriptor instead.
func (*TriggerEStopCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_husky_husky_proto_rawDescGZIP(), []int{4}
}

// ReleaseEStopCommand releases the software E-Stop (hardware E-Stop must be cleared manually).
type ReleaseEStopCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseEStopCommand) Reset() {
	*x = ReleaseEStopCommand{}
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseEStopCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseEStopCommand) ProtoMessage() {}

func (x *ReleaseEStopCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_husky_husky_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseEStopCommand.ProtoReflect.Descriptor instead.
func (*ReleaseEStopCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_husky_husky_proto_rawDescGZIP(), []int{5}
}

var File_internal_extensions_husky_husky_proto protoreflect.FileDescriptor

const file_internal_extensions_husky_husky_proto_rawDesc = "" +
	"\n" +
	"%internal/extensions/husky/husky.proto\x12\x05husky\"\xf9\x02\n" +
	"\x0eHuskyTelemetry\x12/\n" +
	"\n" +
	"drive_mode\x18\x01 \x01(\x0e2\x10.husky.DriveModeR\tdriveMode\x12'\n" +
	"\x0fbattery_voltage\x18\x02 \x01(\x02R\x0ebatteryVoltage\x12>\n" +
	"\x0fbumper_contacts\x18\x03 \x01(\v2\x15.husky.BumperContactsR\x0ebumperContacts\x12)\n" +
	"\x11motor_temp_left_c\x18\x04 \x01(\x02R\x0emotorTempLeftC\x12+\n" +
	"\x12motor_temp_right_c\x18\x05 \x01(\x02R\x0fmotorTempRightC\x12&\n" +
	"\x0fodometry_left_m\x18\x06 \x01(\x02R\rodometryLeftM\x12(\n" +
	"\x10odometry_right_m\x18\a \x01(\x02R\x0eodometryRightM\x12#\n" +
	"\restop_engaged\x18\b \x01(\bR\festopEngaged\"\x8c\x01\n" +
	"\x0eBumperContacts\x12\x1d\n" +
	"\n" +
	"front_left\x18\x01 \x01(\bR\tfrontLeft\x12\x1f\n" +
	"\vfront_right\x18\x02 \x01(\bR\n" +
	"frontRight\x12\x1b\n" +
	"\trear_left\x18\x03 \x01(\bR\brearLeft\x12\x1d\n" +
	"\n" +
	"rear_right\x18\x04 \x01(\bR\trearRight\";\n" +
	"\x13SetDriveModeCommand\x12$\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x10.husky.DriveModeR\x04mode\"?\n" +
	"\x1bSetBumperSensitivityCommand\x12 \n" +
	"\vsensitivity\x18\x01 \x01(\rR\vsensitivity\"\x15\n" +
	"\x13TriggerEStopCommand\"\x15\n" +
	"\x13ReleaseEStopCommand*l\n" +
	"\tDriveMode\x12\x16\n" +
	"\x12DRIVE_MODE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11DRIVE_MODE_MANUAL\x10\x01\x12\x19\n" +
	"\x15DRIVE_MODE_AUTONOMOUS\x10\x02\x12\x15\n" +
	"\x11DRIVE_MODE_GUIDED\x10\x03B>Z<github.com/EthanMBoos/tower-server/internal/extensions/huskyb\x06proto3"

var (
	file_internal_extensions_husky_husky_proto_rawDescOnce sync.Once
	file_internal_extensions_husky_husky_proto_rawDescData []byte
)

func file_internal_extensions_husky_husky_proto_rawDescGZIP() []byte {
	file_internal_extensions_husky_husky_proto_rawDescOnce.Do(func() {
		file_internal_extensions_husky_husky_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_extensions_husky_husky_proto_rawDesc), len(file_internal_extensions_husky_husky_proto_rawDesc)))
	})
	return file_internal_extensions_husky_husky_proto_rawDescData
}

var file_internal_extensions_husky_husky_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_extensions_husky_husky_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_extensions_husky_husky_proto_goTypes = []any{
	(DriveMode)(0),                      // 0: husky.DriveMode
	(*HuskyTelemetry)(nil),              // 1: husky.HuskyTelemetry
	(*BumperContacts)(nil),              // 2: husky.BumperContacts
	(*SetDriveModeCommand)(nil),         // 3: husky.SetDriveModeCommand
	(*SetBumperSensitivityCommand)(nil), // 4: husky.SetBumperSensitivityCommand
	(*TriggerEStopCommand)(nil),         // 5: husky.TriggerEStopCommand
	(*ReleaseEStopCommand)(nil),         // 6: husky.ReleaseEStopCommand
}
var file_internal_extensions_husky_husky_proto_depIdxs = []int32{
	0, // 0: husky.HuskyTelemetry.drive_mode:type_name -> husky.DriveMode
	2, // 1: husky.HuskyTelemetry.bumper_contacts:type_name -> husky.BumperContacts
	0, // 2: husky.SetDriveModeCommand.mode:type_name -> husky.DriveMode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_extensions_husky_husky_proto_init() }
func file_internal_extensions_husky_husky_proto_init() {
	if File_internal_extensions_husky_husky_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_extensions_husky_husky_proto_rawDesc), len(file_internal_extensions_husky_husky_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_extensions_husky_husky_proto_goTypes,
		DependencyIndexes: file_internal_extensions_husky_husky_proto_depIdxs,
		EnumInfos:         file_internal_extensions_husky_husky_proto_enumTypes,
		MessageInfos:      file_internal_extensions_husky_husky_proto_msgTypes,
	}.Build()
	File_internal_extensions_husky_husky_proto = out.File
	file_internal_extensions_husky_husky_proto_goTypes = nil
	file_internal_extensions_husky_husky_proto_depIdxs = nil
}
