// OpenC2 Gateway Protocol
//
// This defines the protobuf schema for vehicle-to-gateway communication.
// Vehicles send telemetry/heartbeats over UDP multicast; gateway sends commands.
// The gateway decodes protobuf and broadcasts JSON to connected UI clients.
//
// See docs/PROTOCOL.md for the JSON format sent to clients.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/proto/openc2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vehicle operational status
// NOTE: Use `optional` field semantics - absence means "not reported", not "unknown".
type VehicleStatus int32

const (
	VehicleStatus_STATUS_ONLINE  VehicleStatus = 0
	VehicleStatus_STATUS_OFFLINE VehicleStatus = 1
	VehicleStatus_STATUS_STANDBY VehicleStatus = 2
)

// Enum value maps for VehicleStatus.
var (
	VehicleStatus_name = map[int32]string{
		0: "STATUS_ONLINE",
		1: "STATUS_OFFLINE",
		2: "STATUS_STANDBY",
	}
	VehicleStatus_value = map[string]int32{
		"STATUS_ONLINE":  0,
		"STATUS_OFFLINE": 1,
		"STATUS_STANDBY": 2,
	}
)

func (x VehicleStatus) Enum() *VehicleStatus {
	p := new(VehicleStatus)
	*p = x
	return p
}

func (x VehicleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[0].Descriptor()
}

func (VehicleStatus) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[0]
}

func (x VehicleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatus.Descriptor instead.
func (VehicleStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{0}
}

// Operating environment/domain
type VehicleEnvironment int32

const (
	VehicleEnvironment_ENV_UNKNOWN VehicleEnvironment = 0
	VehicleEnvironment_ENV_AIR     VehicleEnvironment = 1 // Aerial vehicles (UAV, drones)
	VehicleEnvironment_ENV_GROUND  VehicleEnvironment = 2 // Ground vehicles (UGV, rovers)
	VehicleEnvironment_ENV_MARINE  VehicleEnvironment = 3 // Marine/water surface vessels (USV, boats)
)

// Enum value maps for VehicleEnvironment.
var (
	VehicleEnvironment_name = map[int32]string{
		0: "ENV_UNKNOWN",
		1: "ENV_AIR",
		2: "ENV_GROUND",
		3: "ENV_MARINE",
	}
	VehicleEnvironment_value = map[string]int32{
		"ENV_UNKNOWN": 0,
		"ENV_AIR":     1,
		"ENV_GROUND":  2,
		"ENV_MARINE":  3,
	}
)

func (x VehicleEnvironment) Enum() *VehicleEnvironment {
	p := new(VehicleEnvironment)
	*p = x
	return p
}

func (x VehicleEnvironment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleEnvironment) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[1].Descriptor()
}

func (VehicleEnvironment) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[1]
}

func (x VehicleEnvironment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleEnvironment.Descriptor instead.
func (VehicleEnvironment) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{1}
}

// SensorType enumerates common sensor categories.
// UI can use this to select appropriate visualization (video player, point cloud, etc.)
type SensorType int32

const (
	SensorType_SENSOR_UNKNOWN        SensorType = 0
	SensorType_SENSOR_CAMERA_RGB     SensorType = 1
	SensorType_SENSOR_CAMERA_THERMAL SensorType = 2
	SensorType_SENSOR_CAMERA_DEPTH   SensorType = 3
	SensorType_SENSOR_LIDAR_2D       SensorType = 4
	SensorType_SENSOR_LIDAR_3D       SensorType = 5
	SensorType_SENSOR_RADAR          SensorType = 6
	SensorType_SENSOR_IMU            SensorType = 7
	SensorType_SENSOR_GPS            SensorType = 8
)

// Enum value maps for SensorType.
var (
	SensorType_name = map[int32]string{
		0: "SENSOR_UNKNOWN",
		1: "SENSOR_CAMERA_RGB",
		2: "SENSOR_CAMERA_THERMAL",
		3: "SENSOR_CAMERA_DEPTH",
		4: "SENSOR_LIDAR_2D",
		5: "SENSOR_LIDAR_3D",
		6: "SENSOR_RADAR",
		7: "SENSOR_IMU",
		8: "SENSOR_GPS",
	}
	SensorType_value = map[string]int32{
		"SENSOR_UNKNOWN":        0,
		"SENSOR_CAMERA_RGB":     1,
		"SENSOR_CAMERA_THERMAL": 2,
		"SENSOR_CAMERA_DEPTH":   3,
		"SENSOR_LIDAR_2D":       4,
		"SENSOR_LIDAR_3D":       5,
		"SENSOR_RADAR":          6,
		"SENSOR_IMU":            7,
		"SENSOR_GPS":            8,
	}
)

func (x SensorType) Enum() *SensorType {
	p := new(SensorType)
	*p = x
	return p
}

func (x SensorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensorType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[2].Descriptor()
}

func (SensorType) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[2]
}

func (x SensorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SensorType.Descriptor instead.
func (SensorType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{2}
}

type AlertSeverity int32

const (
	AlertSeverity_SEVERITY_INFO     AlertSeverity = 0
	AlertSeverity_SEVERITY_WARNING  AlertSeverity = 1
	AlertSeverity_SEVERITY_ERROR    AlertSeverity = 2
	AlertSeverity_SEVERITY_CRITICAL AlertSeverity = 3
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "SEVERITY_INFO",
		1: "SEVERITY_WARNING",
		2: "SEVERITY_ERROR",
		3: "SEVERITY_CRITICAL",
	}
	AlertSeverity_value = map[string]int32{
		"SEVERITY_INFO":     0,
		"SEVERITY_WARNING":  1,
		"SEVERITY_ERROR":    2,
		"SEVERITY_CRITICAL": 3,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[3].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[3]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{3}
}

type OperationalMode int32

const (
	OperationalMode_MODE_MANUAL     OperationalMode = 0
	OperationalMode_MODE_AUTONOMOUS OperationalMode = 1
	OperationalMode_MODE_GUIDED     OperationalMode = 2
)

// Enum value maps for OperationalMode.
var (
	OperationalMode_name = map[int32]string{
		0: "MODE_MANUAL",
		1: "MODE_AUTONOMOUS",
		2: "MODE_GUIDED",
	}
	OperationalMode_value = map[string]int32{
		"MODE_MANUAL":     0,
		"MODE_AUTONOMOUS": 1,
		"MODE_GUIDED":     2,
	}
)

func (x OperationalMode) Enum() *OperationalMode {
	p := new(OperationalMode)
	*p = x
	return p
}

func (x OperationalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[4].Descriptor()
}

func (OperationalMode) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[4]
}

func (x OperationalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationalMode.Descriptor instead.
func (OperationalMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{4}
}

// Vehicle ack status values.
// NOTE: "timeout" is a gateway-synthetic status (not in this enum) sent when
// the vehicle doesn't respond within OPENC2_CMD_TIMEOUT. See PROTOCOL.md.
type AckStatus int32

const (
	AckStatus_ACK_ACCEPTED  AckStatus = 0
	AckStatus_ACK_REJECTED  AckStatus = 1
	AckStatus_ACK_COMPLETED AckStatus = 2
	AckStatus_ACK_FAILED    AckStatus = 3
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_ACCEPTED",
		1: "ACK_REJECTED",
		2: "ACK_COMPLETED",
		3: "ACK_FAILED",
	}
	AckStatus_value = map[string]int32{
		"ACK_ACCEPTED":  0,
		"ACK_REJECTED":  1,
		"ACK_COMPLETED": 2,
		"ACK_FAILED":    3,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[5].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[5]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{5}
}

// VehicleMessage is the envelope for all messages from vehicles to gateway.
// The oneof field number acts as the type discriminator in the wire format.
// Gateway unmarshals this first, then switches on which payload is set.
type VehicleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VehicleMessage_Telemetry
	//	*VehicleMessage_Heartbeat
	//	*VehicleMessage_Alert
	//	*VehicleMessage_CommandAck
	Payload       isVehicleMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleMessage) Reset() {
	*x = VehicleMessage{}
	mi := &file_api_proto_openc2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleMessage) ProtoMessage() {}

func (x *VehicleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleMessage.ProtoReflect.Descriptor instead.
func (*VehicleMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleMessage) GetPayload() isVehicleMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VehicleMessage) GetTelemetry() *VehicleTelemetry {
	if x != nil {
		if x, ok := x.Payload.(*VehicleMessage_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *VehicleMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*VehicleMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *VehicleMessage) GetAlert() *Alert {
	if x != nil {
		if x, ok := x.Payload.(*VehicleMessage_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *VehicleMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*VehicleMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

type isVehicleMessage_Payload interface {
	isVehicleMessage_Payload()
}

type VehicleMessage_Telemetry struct {
	Telemetry *VehicleTelemetry `protobuf:"bytes,1,opt,name=telemetry,proto3,oneof"`
}

type VehicleMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type VehicleMessage_Alert struct {
	Alert *Alert `protobuf:"bytes,3,opt,name=alert,proto3,oneof"`
}

type VehicleMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,4,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

func (*VehicleMessage_Telemetry) isVehicleMessage_Payload() {}

func (*VehicleMessage_Heartbeat) isVehicleMessage_Payload() {}

func (*VehicleMessage_Alert) isVehicleMessage_Payload() {}

func (*VehicleMessage_CommandAck) isVehicleMessage_Payload() {}

// VehicleTelemetry is the primary telemetry message sent at high frequency.
// Contains position, velocity, and status information.
//
// NOTE: The `status` field here is for vehicles that include status in every
// telemetry packet. The gateway also tracks status independently based on
// telemetry gaps (see PROTOCOL.md - Offline Detection). Vehicles may omit
// this field if they send separate Heartbeat messages.
//
// TIMESTAMP WARNING: Vehicle clocks are UNTRUSTED (no RTC, no NTP, GPS cold start).
// Use `sequence_num` for ordering, not `timestamp_ms`. The gateway adds its own
// authoritative timestamp (`gts`) when translating to JSON.
type VehicleTelemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique vehicle identifier (e.g., "ugv-husky-07")
	VehicleId string `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	// Unix timestamp in milliseconds - UNTRUSTED, vehicle-local clock
	// Use for display/logging only. See PROTOCOL.md for timestamp semantics.
	TimestampMs int64 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Current position
	Location *Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// Ground speed in meters per second
	SpeedMs float32 `protobuf:"fixed32,4,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"`
	// True heading in degrees [0, 360), 0=North, 90=East
	// NOTE: 360 is normalized to 0. Gateway validates heading < 360.
	HeadingDeg float32 `protobuf:"fixed32,5,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	// Monotonic sequence number for ordering AND deduplication (per-vehicle, wraps at 2^32)
	// Gateway tracks high-water mark per vehicle; seq <= hwm is dropped as duplicate/stale.
	// Use this instead of timestamp for ordering - handles clock skew/reset.
	// See PROTOCOL.md "Gateway Deduplication" for wrap-around handling.
	SequenceNum uint32 `protobuf:"varint,6,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Current operational status (optional - absence means not reported this frame)
	// Use has_status() to check presence. Gateway tracks status independently via telemetry gaps.
	Status *VehicleStatus `protobuf:"varint,7,opt,name=status,proto3,enum=openc2.VehicleStatus,oneof" json:"status,omitempty"`
	// Operating environment
	Environment VehicleEnvironment `protobuf:"varint,8,opt,name=environment,proto3,enum=openc2.VehicleEnvironment" json:"environment,omitempty"`
	// Signal strength (0-5 bars, absence means unknown)
	SignalStrength *uint32 `protobuf:"varint,9,opt,name=signal_strength,json=signalStrength,proto3,oneof" json:"signal_strength,omitempty"`
	// Battery percentage (0-100, absence means unknown)
	BatteryPct *uint32 `protobuf:"varint,10,opt,name=battery_pct,json=batteryPct,proto3,oneof" json:"battery_pct,omitempty"`
	// ── Extension Support ──
	// See docs/EXTENSIBILITY.md for full extension architecture.
	//
	// IMPORTANT: There are TWO extension-related concepts:
	//
	//  1. extensions (this field) = LIVE STATE (10-100Hz telemetry)
	//     → "My battery voltage is 25.6V, drive mode is AUTONOMOUS"
	//     → Changes constantly, sent on every telemetry frame
	//
	//  2. VehicleCapabilities.extensions (in Heartbeat) = VALID COMMANDS (1Hz)
	//     → "I can do setDriveMode and triggerEStop"
	//     → Tells UI which buttons to show
	//
	// List of extension namespaces this vehicle supports (e.g., ["husky", "camera"])
	// Used by UI to filter CommandPanel buttons - only show commands the vehicle can handle.
	// Vehicles SHOULD populate this on every telemetry frame.
	SupportedExtensions []string `protobuf:"bytes,19,rep,name=supported_extensions,json=supportedExtensions,proto3" json:"supported_extensions,omitempty"`
	// Extension data by namespace. Each extension is versioned independently.
	// Key = namespace (e.g., "husky"), Value = versioned extension payload.
	// Gateway decodes these via registered codecs and translates to JSON for UI.
	// Unknown extensions are passed through with error metadata (graceful degradation).
	Extensions    map[string]*ExtensionData `protobuf:"bytes,20,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTelemetry) Reset() {
	*x = VehicleTelemetry{}
	mi := &file_api_proto_openc2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTelemetry) ProtoMessage() {}

func (x *VehicleTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTelemetry.ProtoReflect.Descriptor instead.
func (*VehicleTelemetry) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleTelemetry) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *VehicleTelemetry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *VehicleTelemetry) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *VehicleTelemetry) GetSpeedMs() float32 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

func (x *VehicleTelemetry) GetHeadingDeg() float32 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *VehicleTelemetry) GetSequenceNum() uint32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *VehicleTelemetry) GetStatus() VehicleStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return VehicleStatus_STATUS_ONLINE
}

func (x *VehicleTelemetry) GetEnvironment() VehicleEnvironment {
	if x != nil {
		return x.Environment
	}
	return VehicleEnvironment_ENV_UNKNOWN
}

func (x *VehicleTelemetry) GetSignalStrength() uint32 {
	if x != nil && x.SignalStrength != nil {
		return *x.SignalStrength
	}
	return 0
}

func (x *VehicleTelemetry) GetBatteryPct() uint32 {
	if x != nil && x.BatteryPct != nil {
		return *x.BatteryPct
	}
	return 0
}

func (x *VehicleTelemetry) GetSupportedExtensions() []string {
	if x != nil {
		return x.SupportedExtensions
	}
	return nil
}

func (x *VehicleTelemetry) GetExtensions() map[string]*ExtensionData {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// ExtensionData wraps extension payloads with version metadata.
// This allows schema evolution per-extension without breaking the gateway.
type ExtensionData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version for this extension's payload format.
	// Codecs use this to select the correct decoder.
	// Start at 1; increment on breaking changes to payload schema.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Serialized extension-specific proto (e.g., HuskyTelemetry).
	// Opaque to gateway core; decoded by namespace-specific codec.
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionData) Reset() {
	*x = ExtensionData{}
	mi := &file_api_proto_openc2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionData) ProtoMessage() {}

func (x *ExtensionData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionData.ProtoReflect.Descriptor instead.
func (*ExtensionData) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{2}
}

func (x *ExtensionData) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ExtensionData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Geographic location in WGS84 coordinates
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude in degrees (-90 to 90)
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude in degrees (-180 to 180)
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Altitude MSL in meters
	AltitudeMslM  float32 `protobuf:"fixed32,3,opt,name=altitude_msl_m,json=altitudeMslM,proto3" json:"altitude_msl_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_api_proto_openc2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAltitudeMslM() float32 {
	if x != nil {
		return x.AltitudeMslM
	}
	return 0
}

// Heartbeat message sent periodically to confirm connectivity
// Note: battery_pct is only in VehicleTelemetry (single source of truth)
type Heartbeat struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	VehicleId   string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Status      VehicleStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=openc2.VehicleStatus" json:"status,omitempty"`
	UptimeMs    int64                  `protobuf:"varint,4,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	// Capability advertisement - tells gateway/UI what this vehicle supports.
	// Sent on every heartbeat so capabilities can change at runtime
	// (e.g., sensor added, extension module loaded).
	Capabilities *VehicleCapabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Vehicle type identifier for UI auto-matching to Vehicle profiles.
	// Example: "clearpath-husky-a200", "skydio-x2d", "bluerov2"
	// UI matches this against Vehicle.name or Vehicle.tags[] to automatically
	// link VehicleInstance to the correct Vehicle definition (static specs).
	// If no match found, UI can prompt operator or use a generic profile.
	VehicleType   string `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_openc2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Heartbeat) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_STATUS_ONLINE
}

func (x *Heartbeat) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *Heartbeat) GetCapabilities() *VehicleCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Heartbeat) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

// VehicleCapabilities advertises what commands/features a vehicle supports.
// This prevents the UI from showing buttons for unsupported actions and allows
// the gateway to fail-fast on invalid commands.
//
// DESIGN: Sent on EVERY heartbeat (1Hz), not just once.
//
// Why repeat on every heartbeat?
// - Stateless robustness: Gateway restart → learns caps from next heartbeat
// - UDP is unreliable: Lost packet recovers in 1 second
// - Capabilities CAN change at runtime:
//   - Sensor failure → remove from sensors[]
//   - Battery critical → remove "goto" from supported_commands (can only RTL)
//   - E-Stop engaged → remove movement commands temporarily
//   - Hot-plugged hardware → add new sensor
//   - Firmware OTA update → new commands become available
//
// Industry precedent: MAVLink HEARTBEAT, ROS2 DDS, DIS entity state all
// advertise capabilities continuously for the same reasons.
//
// CRITICAL: Without capabilities, teams WILL fork the UI to hide buttons for
// vehicles that can't stop (fixed-wing), return home (tethered ROV), etc.
type VehicleCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Core commands this vehicle supports.
	// Values: "goto", "stop", "return_home", "set_mode", "set_speed"
	// An empty list means observation-only (no commands accepted).
	SupportedCommands []string `protobuf:"bytes,1,rep,name=supported_commands,json=supportedCommands,proto3" json:"supported_commands,omitempty"`
	// Extension capabilities with specific supported actions.
	// More granular than just namespace - includes which commands within each extension
	// the vehicle actually implements.
	Extensions []*ExtensionCapability `protobuf:"bytes,2,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Whether vehicle accepts mission waypoint sequences.
	// If false, only single-point commands (goto) are supported.
	SupportsMissions bool `protobuf:"varint,3,opt,name=supports_missions,json=supportsMissions,proto3" json:"supports_missions,omitempty"`
	// Sensors attached to this vehicle.
	// Used by UI to display camera feeds, visualize sensor FOV, etc.
	Sensors       []*SensorCapability `protobuf:"bytes,4,rep,name=sensors,proto3" json:"sensors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleCapabilities) Reset() {
	*x = VehicleCapabilities{}
	mi := &file_api_proto_openc2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleCapabilities) ProtoMessage() {}

func (x *VehicleCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleCapabilities.ProtoReflect.Descriptor instead.
func (*VehicleCapabilities) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{5}
}

func (x *VehicleCapabilities) GetSupportedCommands() []string {
	if x != nil {
		return x.SupportedCommands
	}
	return nil
}

func (x *VehicleCapabilities) GetExtensions() []*ExtensionCapability {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *VehicleCapabilities) GetSupportsMissions() bool {
	if x != nil {
		return x.SupportsMissions
	}
	return false
}

func (x *VehicleCapabilities) GetSensors() []*SensorCapability {
	if x != nil {
		return x.Sensors
	}
	return nil
}

// ExtensionCapability advertises which actions a vehicle supports within an extension.
// This enables fine-grained filtering: a vehicle might support the "husky" extension
// but only implement "setDriveMode" and not "triggerEstop".
type ExtensionCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extension namespace (e.g., "husky", "camera")
	// Must match a registered extension codec in the gateway.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Schema version this vehicle implements.
	// Gateway can use this to select appropriate codec version.
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Specific actions this vehicle supports within the extension.
	// If empty, vehicle supports ALL actions defined in the manifest.
	// If populated, vehicle ONLY supports these specific actions.
	// Example: ["setDriveMode", "setBumperSensitivity"] (but not "triggerEstop")
	SupportedActions []string `protobuf:"bytes,3,rep,name=supported_actions,json=supportedActions,proto3" json:"supported_actions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtensionCapability) Reset() {
	*x = ExtensionCapability{}
	mi := &file_api_proto_openc2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionCapability) ProtoMessage() {}

func (x *ExtensionCapability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionCapability.ProtoReflect.Descriptor instead.
func (*ExtensionCapability) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{6}
}

func (x *ExtensionCapability) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExtensionCapability) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ExtensionCapability) GetSupportedActions() []string {
	if x != nil {
		return x.SupportedActions
	}
	return nil
}

// SensorCapability describes an attached sensor with stream info.
// This is a CORE protocol feature (not an extension) because sensors are
// cross-cutting — nearly every robotics project needs camera/LiDAR support.
type SensorCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique sensor identifier on this vehicle (e.g., "front_camera", "lidar_1")
	SensorId string `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	// Sensor type for UI rendering hints
	Type SensorType `protobuf:"varint,2,opt,name=type,proto3,enum=openc2.SensorType" json:"type,omitempty"`
	// Stream URL if applicable (rtsp://, http://, ws://)
	// Empty for non-streaming sensors (IMU, GPS)
	StreamUrl string `protobuf:"bytes,3,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	// Physical mounting position/orientation (for FOV visualization)
	Mount *SensorMount `protobuf:"bytes,4,opt,name=mount,proto3" json:"mount,omitempty"`
	// Type-specific metadata (resolution, FOV, etc.)
	// Keys are sensor-type-specific; see SensorType documentation.
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorCapability) Reset() {
	*x = SensorCapability{}
	mi := &file_api_proto_openc2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorCapability) ProtoMessage() {}

func (x *SensorCapability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorCapability.ProtoReflect.Descriptor instead.
func (*SensorCapability) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{7}
}

func (x *SensorCapability) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *SensorCapability) GetType() SensorType {
	if x != nil {
		return x.Type
	}
	return SensorType_SENSOR_UNKNOWN
}

func (x *SensorCapability) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *SensorCapability) GetMount() *SensorMount {
	if x != nil {
		return x.Mount
	}
	return nil
}

func (x *SensorCapability) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SensorMount describes the physical mounting of a sensor.
// Used by UI to visualize sensor FOV cones on the map.
type SensorMount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position offset from vehicle origin (meters, body frame)
	// X = forward, Y = left, Z = up
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	// Orientation (Euler angles in degrees, body frame)
	// Roll/pitch/yaw convention: X-forward, Y-left, Z-up
	Roll          float32 `protobuf:"fixed32,4,opt,name=roll,proto3" json:"roll,omitempty"`
	Pitch         float32 `protobuf:"fixed32,5,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Yaw           float32 `protobuf:"fixed32,6,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorMount) Reset() {
	*x = SensorMount{}
	mi := &file_api_proto_openc2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorMount) ProtoMessage() {}

func (x *SensorMount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorMount.ProtoReflect.Descriptor instead.
func (*SensorMount) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{8}
}

func (x *SensorMount) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SensorMount) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SensorMount) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SensorMount) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *SensorMount) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *SensorMount) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

// Alert message for warnings, errors, and events
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Severity      AlertSeverity          `protobuf:"varint,3,opt,name=severity,proto3,enum=openc2.AlertSeverity" json:"severity,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`         // Machine-readable code (e.g., "GEOFENCE_BREACH")
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`   // Human-readable description
	Location      *Location              `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"` // Optional: where the alert occurred
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_api_proto_openc2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{9}
}

func (x *Alert) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Alert) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Alert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_SEVERITY_INFO
}

func (x *Alert) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Command is the envelope for all commands sent to vehicles
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique command ID for tracking acknowledgments
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Target vehicle ID
	VehicleId string `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	// Unix timestamp in milliseconds (UTC)
	TimestampMs int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Command payload (one of the following)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_Goto
	//	*Command_Stop
	//	*Command_ReturnHome
	//	*Command_SetMode
	//	*Command_SetSpeed
	//	*Command_Extension
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_proto_openc2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{10}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Command) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetGoto() *GotoCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Goto); ok {
			return x.Goto
		}
	}
	return nil
}

func (x *Command) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *Command) GetReturnHome() *ReturnHomeCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_ReturnHome); ok {
			return x.ReturnHome
		}
	}
	return nil
}

func (x *Command) GetSetMode() *SetModeCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_SetMode); ok {
			return x.SetMode
		}
	}
	return nil
}

func (x *Command) GetSetSpeed() *SetSpeedCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_SetSpeed); ok {
			return x.SetSpeed
		}
	}
	return nil
}

func (x *Command) GetExtension() *ExtensionCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_Goto struct {
	Goto *GotoCommand `protobuf:"bytes,10,opt,name=goto,proto3,oneof"`
}

type Command_Stop struct {
	Stop *StopCommand `protobuf:"bytes,11,opt,name=stop,proto3,oneof"`
}

type Command_ReturnHome struct {
	ReturnHome *ReturnHomeCommand `protobuf:"bytes,12,opt,name=return_home,json=returnHome,proto3,oneof"`
}

type Command_SetMode struct {
	SetMode *SetModeCommand `protobuf:"bytes,13,opt,name=set_mode,json=setMode,proto3,oneof"`
}

type Command_SetSpeed struct {
	SetSpeed *SetSpeedCommand `protobuf:"bytes,14,opt,name=set_speed,json=setSpeed,proto3,oneof"`
}

type Command_Extension struct {
	Extension *ExtensionCommand `protobuf:"bytes,20,opt,name=extension,proto3,oneof"` // Extension-defined commands
}

func (*Command_Goto) isCommand_Payload() {}

func (*Command_Stop) isCommand_Payload() {}

func (*Command_ReturnHome) isCommand_Payload() {}

func (*Command_SetMode) isCommand_Payload() {}

func (*Command_SetSpeed) isCommand_Payload() {}

func (*Command_Extension) isCommand_Payload() {}

// ExtensionCommand routes custom commands to extension-specific handlers.
// The gateway encodes this from JSON and broadcasts to vehicles.
// Vehicles decode based on namespace and action.
type ExtensionCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extension namespace (e.g., "husky") - must match a registered codec
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Action within the extension (e.g., "setDriveMode")
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Schema version for this command's payload format
	// Allows command schemas to evolve independently of telemetry schemas
	Version uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Serialized extension-specific command proto (e.g., SetDriveModeCommand)
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionCommand) Reset() {
	*x = ExtensionCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionCommand) ProtoMessage() {}

func (x *ExtensionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionCommand.ProtoReflect.Descriptor instead.
func (*ExtensionCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{11}
}

func (x *ExtensionCommand) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExtensionCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExtensionCommand) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ExtensionCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Navigate to a destination
type GotoCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *Location              `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`          // Includes altitude for aerial vehicles
	SpeedMs       float32                `protobuf:"fixed32,2,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"` // Target speed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GotoCommand) Reset() {
	*x = GotoCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GotoCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GotoCommand) ProtoMessage() {}

func (x *GotoCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GotoCommand.ProtoReflect.Descriptor instead.
func (*GotoCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{12}
}

func (x *GotoCommand) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *GotoCommand) GetSpeedMs() float32 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

// Emergency stop
type StopCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCommand) Reset() {
	*x = StopCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCommand) ProtoMessage() {}

func (x *StopCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCommand.ProtoReflect.Descriptor instead.
func (*StopCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{13}
}

// Return to home/launch position
type ReturnHomeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnHomeCommand) Reset() {
	*x = ReturnHomeCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnHomeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnHomeCommand) ProtoMessage() {}

func (x *ReturnHomeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnHomeCommand.ProtoReflect.Descriptor instead.
func (*ReturnHomeCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{14}
}

// Set operational mode
type SetModeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          OperationalMode        `protobuf:"varint,1,opt,name=mode,proto3,enum=openc2.OperationalMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModeCommand) Reset() {
	*x = SetModeCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModeCommand) ProtoMessage() {}

func (x *SetModeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModeCommand.ProtoReflect.Descriptor instead.
func (*SetModeCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{15}
}

func (x *SetModeCommand) GetMode() OperationalMode {
	if x != nil {
		return x.Mode
	}
	return OperationalMode_MODE_MANUAL
}

// Set target speed
type SetSpeedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeedMs       float32                `protobuf:"fixed32,1,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpeedCommand) Reset() {
	*x = SetSpeedCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpeedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpeedCommand) ProtoMessage() {}

func (x *SetSpeedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpeedCommand.ProtoReflect.Descriptor instead.
func (*SetSpeedCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{16}
}

func (x *SetSpeedCommand) GetSpeedMs() float32 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

// GatewayMessage is the envelope for all messages from gateway to vehicles.
// Vehicles receive this on multicast 239.255.0.2:14551, unmarshal, and switch
// on which payload is set. Commands are filtered by vehicle_id; heartbeats
// are processed by all vehicles.
type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayMessage_Command
	//	*GatewayMessage_Heartbeat
	Payload       isGatewayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_api_proto_openc2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{17}
}

func (x *GatewayMessage) GetPayload() isGatewayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *GatewayMessage) GetHeartbeat() *GatewayHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isGatewayMessage_Payload interface {
	isGatewayMessage_Payload()
}

type GatewayMessage_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type GatewayMessage_Heartbeat struct {
	Heartbeat *GatewayHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*GatewayMessage_Command) isGatewayMessage_Payload() {}

func (*GatewayMessage_Heartbeat) isGatewayMessage_Payload() {}

// GatewayHeartbeat is sent periodically (every 1s) to let vehicles detect
// gateway connectivity loss. If a vehicle doesn't receive a heartbeat for
// OPENC2_GATEWAY_TIMEOUT (default 5s), it MUST trigger failsafe behavior.
//
// Failsafe modes (configured via OPENC2_FAILSAFE_MODE):
//   - RTL: Return to home/launch position (default for aerial)
//   - HOLD: Stop and hold current position (default for ground)
//   - CONTINUE: Continue autonomous mission
//   - LAND: Immediate landing (aerial only)
//
// See PROTOCOL.md "Gateway Loss Detection" for full behavioral specification.
//
// Vehicles SHOULD NOT use this for time sync - gateway clock is authoritative
// for the UI, but vehicles should rely on GPS/internal clocks for autonomy.
type GatewayHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix timestamp in milliseconds (UTC) - gateway's authoritative clock
	TimestampMs int64 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Monotonic sequence number for ordering/loss detection (wraps at 2^32)
	// Vehicles can detect packet loss by tracking gaps in sequence.
	SequenceNum uint32 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Number of currently connected UI clients (informational)
	ConnectedClients uint32 `protobuf:"varint,3,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	// Number of vehicles in registry (informational)
	TrackedVehicles uint32 `protobuf:"varint,4,opt,name=tracked_vehicles,json=trackedVehicles,proto3" json:"tracked_vehicles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GatewayHeartbeat) Reset() {
	*x = GatewayHeartbeat{}
	mi := &file_api_proto_openc2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHeartbeat) ProtoMessage() {}

func (x *GatewayHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHeartbeat.ProtoReflect.Descriptor instead.
func (*GatewayHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{18}
}

func (x *GatewayHeartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *GatewayHeartbeat) GetSequenceNum() uint32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *GatewayHeartbeat) GetConnectedClients() uint32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *GatewayHeartbeat) GetTrackedVehicles() uint32 {
	if x != nil {
		return x.TrackedVehicles
	}
	return 0
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	VehicleId     string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Status        AckStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=openc2.AckStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // Human-readable status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_api_proto_openc2_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{19}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *CommandAck) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *CommandAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_ACCEPTED
}

func (x *CommandAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_openc2_proto protoreflect.FileDescriptor

const file_api_proto_openc2_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/openc2.proto\x12\x06openc2\"\xe6\x01\n" +
	"\x0eVehicleMessage\x128\n" +
	"\ttelemetry\x18\x01 \x01(\v2\x18.openc2.VehicleTelemetryH\x00R\ttelemetry\x121\n" +
	"\theartbeat\x18\x02 \x01(\v2\x11.openc2.HeartbeatH\x00R\theartbeat\x12%\n" +
	"\x05alert\x18\x03 \x01(\v2\r.openc2.AlertH\x00R\x05alert\x125\n" +
	"\vcommand_ack\x18\x04 \x01(\v2\x12.openc2.CommandAckH\x00R\n" +
	"commandAckB\t\n" +
	"\apayload\"\xa9\x05\n" +
	"\x10VehicleTelemetry\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12,\n" +
	"\blocation\x18\x03 \x01(\v2\x10.openc2.LocationR\blocation\x12\x19\n" +
	"\bspeed_ms\x18\x04 \x01(\x02R\aspeedMs\x12\x1f\n" +
	"\vheading_deg\x18\x05 \x01(\x02R\n" +
	"headingDeg\x12!\n" +
	"\fsequence_num\x18\x06 \x01(\rR\vsequenceNum\x122\n" +
	"\x06status\x18\a \x01(\x0e2\x15.openc2.VehicleStatusH\x00R\x06status\x88\x01\x01\x12<\n" +
	"\venvironment\x18\b \x01(\x0e2\x1a.openc2.VehicleEnvironmentR\venvironment\x12,\n" +
	"\x0fsignal_strength\x18\t \x01(\rH\x01R\x0esignalStrength\x88\x01\x01\x12$\n" +
	"\vbattery_pct\x18\n" +
	" \x01(\rH\x02R\n" +
	"batteryPct\x88\x01\x01\x121\n" +
	"\x14supported_extensions\x18\x13 \x03(\tR\x13supportedExtensions\x12H\n" +
	"\n" +
	"extensions\x18\x14 \x03(\v2(.openc2.VehicleTelemetry.ExtensionsEntryR\n" +
	"extensions\x1aT\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.openc2.ExtensionDataR\x05value:\x028\x01B\t\n" +
	"\a_statusB\x12\n" +
	"\x10_signal_strengthB\x0e\n" +
	"\f_battery_pct\"C\n" +
	"\rExtensionData\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"j\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12$\n" +
	"\x0ealtitude_msl_m\x18\x03 \x01(\x02R\faltitudeMslM\"\xfd\x01\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.openc2.VehicleStatusR\x06status\x12\x1b\n" +
	"\tuptime_ms\x18\x04 \x01(\x03R\buptimeMs\x12?\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x1b.openc2.VehicleCapabilitiesR\fcapabilities\x12!\n" +
	"\fvehicle_type\x18\x06 \x01(\tR\vvehicleType\"\xe2\x01\n" +
	"\x13VehicleCapabilities\x12-\n" +
	"\x12supported_commands\x18\x01 \x03(\tR\x11supportedCommands\x12;\n" +
	"\n" +
	"extensions\x18\x02 \x03(\v2\x1b.openc2.ExtensionCapabilityR\n" +
	"extensions\x12+\n" +
	"\x11supports_missions\x18\x03 \x01(\bR\x10supportsMissions\x122\n" +
	"\asensors\x18\x04 \x03(\v2\x18.openc2.SensorCapabilityR\asensors\"z\n" +
	"\x13ExtensionCapability\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12+\n" +
	"\x11supported_actions\x18\x03 \x03(\tR\x10supportedActions\"\xa2\x02\n" +
	"\x10SensorCapability\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.openc2.SensorTypeR\x04type\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x03 \x01(\tR\tstreamUrl\x12)\n" +
	"\x05mount\x18\x04 \x01(\v2\x13.openc2.SensorMountR\x05mount\x12B\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2&.openc2.SensorCapability.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\vSensorMount\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x12\n" +
	"\x04roll\x18\x04 \x01(\x02R\x04roll\x12\x14\n" +
	"\x05pitch\x18\x05 \x01(\x02R\x05pitch\x12\x10\n" +
	"\x03yaw\x18\x06 \x01(\x02R\x03yaw\"\xd8\x01\n" +
	"\x05Alert\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x121\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x15.openc2.AlertSeverityR\bseverity\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12,\n" +
	"\blocation\x18\x06 \x01(\v2\x10.openc2.LocationR\blocation\"\xb0\x03\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12)\n" +
	"\x04goto\x18\n" +
	" \x01(\v2\x13.openc2.GotoCommandH\x00R\x04goto\x12)\n" +
	"\x04stop\x18\v \x01(\v2\x13.openc2.StopCommandH\x00R\x04stop\x12<\n" +
	"\vreturn_home\x18\f \x01(\v2\x19.openc2.ReturnHomeCommandH\x00R\n" +
	"returnHome\x123\n" +
	"\bset_mode\x18\r \x01(\v2\x16.openc2.SetModeCommandH\x00R\asetMode\x126\n" +
	"\tset_speed\x18\x0e \x01(\v2\x17.openc2.SetSpeedCommandH\x00R\bsetSpeed\x128\n" +
	"\textension\x18\x14 \x01(\v2\x18.openc2.ExtensionCommandH\x00R\textensionB\t\n" +
	"\apayload\"|\n" +
	"\x10ExtensionCommand\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\\\n" +
	"\vGotoCommand\x122\n" +
	"\vdestination\x18\x01 \x01(\v2\x10.openc2.LocationR\vdestination\x12\x19\n" +
	"\bspeed_ms\x18\x02 \x01(\x02R\aspeedMs\"\r\n" +
	"\vStopCommand\"\x13\n" +
	"\x11ReturnHomeCommand\"=\n" +
	"\x0eSetModeCommand\x12+\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x17.openc2.OperationalModeR\x04mode\",\n" +
	"\x0fSetSpeedCommand\x12\x19\n" +
	"\bspeed_ms\x18\x01 \x01(\x02R\aspeedMs\"\x82\x01\n" +
	"\x0eGatewayMessage\x12+\n" +
	"\acommand\x18\x01 \x01(\v2\x0f.openc2.CommandH\x00R\acommand\x128\n" +
	"\theartbeat\x18\x02 \x01(\v2\x18.openc2.GatewayHeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xb0\x01\n" +
	"\x10GatewayHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\rR\vsequenceNum\x12+\n" +
	"\x11connected_clients\x18\x03 \x01(\rR\x10connectedClients\x12)\n" +
	"\x10tracked_vehicles\x18\x04 \x01(\rR\x0ftrackedVehicles\"\xb2\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.openc2.AckStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*J\n" +
	"\rVehicleStatus\x12\x11\n" +
	"\rSTATUS_ONLINE\x10\x00\x12\x12\n" +
	"\x0eSTATUS_OFFLINE\x10\x01\x12\x12\n" +
	"\x0eSTATUS_STANDBY\x10\x02*R\n" +
	"\x12VehicleEnvironment\x12\x0f\n" +
	"\vENV_UNKNOWN\x10\x00\x12\v\n" +
	"\aENV_AIR\x10\x01\x12\x0e\n" +
	"\n" +
	"ENV_GROUND\x10\x02\x12\x0e\n" +
	"\n" +
	"ENV_MARINE\x10\x03*\xc7\x01\n" +
	"\n" +
	"SensorType\x12\x12\n" +
	"\x0eSENSOR_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11SENSOR_CAMERA_RGB\x10\x01\x12\x19\n" +
	"\x15SENSOR_CAMERA_THERMAL\x10\x02\x12\x17\n" +
	"\x13SENSOR_CAMERA_DEPTH\x10\x03\x12\x13\n" +
	"\x0fSENSOR_LIDAR_2D\x10\x04\x12\x13\n" +
	"\x0fSENSOR_LIDAR_3D\x10\x05\x12\x10\n" +
	"\fSENSOR_RADAR\x10\x06\x12\x0e\n" +
	"\n" +
	"SENSOR_IMU\x10\a\x12\x0e\n" +
	"\n" +
	"SENSOR_GPS\x10\b*c\n" +
	"\rAlertSeverity\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x00\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x01\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x02\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x03*H\n" +
	"\x0fOperationalMode\x12\x0f\n" +
	"\vMODE_MANUAL\x10\x00\x12\x13\n" +
	"\x0fMODE_AUTONOMOUS\x10\x01\x12\x0f\n" +
	"\vMODE_GUIDED\x10\x02*R\n" +
	"\tAckStatus\x12\x10\n" +
	"\fACK_ACCEPTED\x10\x00\x12\x10\n" +
	"\fACK_REJECTED\x10\x01\x12\x11\n" +
	"\rACK_COMPLETED\x10\x02\x12\x0e\n" +
	"\n" +
	"ACK_FAILED\x10\x03B0Z.github.com/EthanMBoos/openc2-gateway/api/protob\x06proto3"

var (
	file_api_proto_openc2_proto_rawDescOnce sync.Once
	file_api_proto_openc2_proto_rawDescData []byte
)

func file_api_proto_openc2_proto_rawDescGZIP() []byte {
	file_api_proto_openc2_proto_rawDescOnce.Do(func() {
		file_api_proto_openc2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_openc2_proto_rawDesc), len(file_api_proto_openc2_proto_rawDesc)))
	})
	return file_api_proto_openc2_proto_rawDescData
}

var file_api_proto_openc2_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_proto_openc2_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_openc2_proto_goTypes = []any{
	(VehicleStatus)(0),          // 0: openc2.VehicleStatus
	(VehicleEnvironment)(0),     // 1: openc2.VehicleEnvironment
	(SensorType)(0),             // 2: openc2.SensorType
	(AlertSeverity)(0),          // 3: openc2.AlertSeverity
	(OperationalMode)(0),        // 4: openc2.OperationalMode
	(AckStatus)(0),              // 5: openc2.AckStatus
	(*VehicleMessage)(nil),      // 6: openc2.VehicleMessage
	(*VehicleTelemetry)(nil),    // 7: openc2.VehicleTelemetry
	(*ExtensionData)(nil),       // 8: openc2.ExtensionData
	(*Location)(nil),            // 9: openc2.Location
	(*Heartbeat)(nil),           // 10: openc2.Heartbeat
	(*VehicleCapabilities)(nil), // 11: openc2.VehicleCapabilities
	(*ExtensionCapability)(nil), // 12: openc2.ExtensionCapability
	(*SensorCapability)(nil),    // 13: openc2.SensorCapability
	(*SensorMount)(nil),         // 14: openc2.SensorMount
	(*Alert)(nil),               // 15: openc2.Alert
	(*Command)(nil),             // 16: openc2.Command
	(*ExtensionCommand)(nil),    // 17: openc2.ExtensionCommand
	(*GotoCommand)(nil),         // 18: openc2.GotoCommand
	(*StopCommand)(nil),         // 19: openc2.StopCommand
	(*ReturnHomeCommand)(nil),   // 20: openc2.ReturnHomeCommand
	(*SetModeCommand)(nil),      // 21: openc2.SetModeCommand
	(*SetSpeedCommand)(nil),     // 22: openc2.SetSpeedCommand
	(*GatewayMessage)(nil),      // 23: openc2.GatewayMessage
	(*GatewayHeartbeat)(nil),    // 24: openc2.GatewayHeartbeat
	(*CommandAck)(nil),          // 25: openc2.CommandAck
	nil,                         // 26: openc2.VehicleTelemetry.ExtensionsEntry
	nil,                         // 27: openc2.SensorCapability.MetadataEntry
}
var file_api_proto_openc2_proto_depIdxs = []int32{
	7,  // 0: openc2.VehicleMessage.telemetry:type_name -> openc2.VehicleTelemetry
	10, // 1: openc2.VehicleMessage.heartbeat:type_name -> openc2.Heartbeat
	15, // 2: openc2.VehicleMessage.alert:type_name -> openc2.Alert
	25, // 3: openc2.VehicleMessage.command_ack:type_name -> openc2.CommandAck
	9,  // 4: openc2.VehicleTelemetry.location:type_name -> openc2.Location
	0,  // 5: openc2.VehicleTelemetry.status:type_name -> openc2.VehicleStatus
	1,  // 6: openc2.VehicleTelemetry.environment:type_name -> openc2.VehicleEnvironment
	26, // 7: openc2.VehicleTelemetry.extensions:type_name -> openc2.VehicleTelemetry.ExtensionsEntry
	0,  // 8: openc2.Heartbeat.status:type_name -> openc2.VehicleStatus
	11, // 9: openc2.Heartbeat.capabilities:type_name -> openc2.VehicleCapabilities
	12, // 10: openc2.VehicleCapabilities.extensions:type_name -> openc2.ExtensionCapability
	13, // 11: openc2.VehicleCapabilities.sensors:type_name -> openc2.SensorCapability
	2,  // 12: openc2.SensorCapability.type:type_name -> openc2.SensorType
	14, // 13: openc2.SensorCapability.mount:type_name -> openc2.SensorMount
	27, // 14: openc2.SensorCapability.metadata:type_name -> openc2.SensorCapability.MetadataEntry
	3,  // 15: openc2.Alert.severity:type_name -> openc2.AlertSeverity
	9,  // 16: openc2.Alert.location:type_name -> openc2.Location
	18, // 17: openc2.Command.goto:type_name -> openc2.GotoCommand
	19, // 18: openc2.Command.stop:type_name -> openc2.StopCommand
	20, // 19: openc2.Command.return_home:type_name -> openc2.ReturnHomeCommand
	21, // 20: openc2.Command.set_mode:type_name -> openc2.SetModeCommand
	22, // 21: openc2.Command.set_speed:type_name -> openc2.SetSpeedCommand
	17, // 22: openc2.Command.extension:type_name -> openc2.ExtensionCommand
	9,  // 23: openc2.GotoCommand.destination:type_name -> openc2.Location
	4,  // 24: openc2.SetModeCommand.mode:type_name -> openc2.OperationalMode
	16, // 25: openc2.GatewayMessage.command:type_name -> openc2.Command
	24, // 26: openc2.GatewayMessage.heartbeat:type_name -> openc2.GatewayHeartbeat
	5,  // 27: openc2.CommandAck.status:type_name -> openc2.AckStatus
	8,  // 28: openc2.VehicleTelemetry.ExtensionsEntry.value:type_name -> openc2.ExtensionData
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_api_proto_openc2_proto_init() }
func file_api_proto_openc2_proto_init() {
	if File_api_proto_openc2_proto != nil {
		return
	}
	file_api_proto_openc2_proto_msgTypes[0].OneofWrappers = []any{
		(*VehicleMessage_Telemetry)(nil),
		(*VehicleMessage_Heartbeat)(nil),
		(*VehicleMessage_Alert)(nil),
		(*VehicleMessage_CommandAck)(nil),
	}
	file_api_proto_openc2_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_openc2_proto_msgTypes[10].OneofWrappers = []any{
		(*Command_Goto)(nil),
		(*Command_Stop)(nil),
		(*Command_ReturnHome)(nil),
		(*Command_SetMode)(nil),
		(*Command_SetSpeed)(nil),
		(*Command_Extension)(nil),
	}
	file_api_proto_openc2_proto_msgTypes[17].OneofWrappers = []any{
		(*GatewayMessage_Command)(nil),
		(*GatewayMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_openc2_proto_rawDesc), len(file_api_proto_openc2_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_openc2_proto_goTypes,
		DependencyIndexes: file_api_proto_openc2_proto_depIdxs,
		EnumInfos:         file_api_proto_openc2_proto_enumTypes,
		MessageInfos:      file_api_proto_openc2_proto_msgTypes,
	}.Build()
	File_api_proto_openc2_proto = out.File
	file_api_proto_openc2_proto_goTypes = nil
	file_api_proto_openc2_proto_depIdxs = nil
}
