// OpenC2 Gateway Protocol
//
// This defines the protobuf schema for vehicle-to-gateway communication.
// Vehicles send telemetry/heartbeats over UDP multicast; gateway sends commands.
// The gateway decodes protobuf and broadcasts JSON to connected UI clients.
//
// See docs/PROTOCOL.md for the JSON format sent to clients.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/proto/openc2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vehicle operational status
// NOTE: Use `optional` field semantics - absence means "not reported", not "unknown".
type VehicleStatus int32

const (
	VehicleStatus_STATUS_ONLINE  VehicleStatus = 0
	VehicleStatus_STATUS_OFFLINE VehicleStatus = 1
	VehicleStatus_STATUS_STANDBY VehicleStatus = 2
)

// Enum value maps for VehicleStatus.
var (
	VehicleStatus_name = map[int32]string{
		0: "STATUS_ONLINE",
		1: "STATUS_OFFLINE",
		2: "STATUS_STANDBY",
	}
	VehicleStatus_value = map[string]int32{
		"STATUS_ONLINE":  0,
		"STATUS_OFFLINE": 1,
		"STATUS_STANDBY": 2,
	}
)

func (x VehicleStatus) Enum() *VehicleStatus {
	p := new(VehicleStatus)
	*p = x
	return p
}

func (x VehicleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[0].Descriptor()
}

func (VehicleStatus) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[0]
}

func (x VehicleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatus.Descriptor instead.
func (VehicleStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{0}
}

// Operating environment/domain
type VehicleEnvironment int32

const (
	VehicleEnvironment_ENV_UNKNOWN    VehicleEnvironment = 0
	VehicleEnvironment_ENV_AIR        VehicleEnvironment = 1
	VehicleEnvironment_ENV_GROUND     VehicleEnvironment = 2
	VehicleEnvironment_ENV_SURFACE    VehicleEnvironment = 3 // Water surface
	VehicleEnvironment_ENV_SUBSURFACE VehicleEnvironment = 4 // Underwater
)

// Enum value maps for VehicleEnvironment.
var (
	VehicleEnvironment_name = map[int32]string{
		0: "ENV_UNKNOWN",
		1: "ENV_AIR",
		2: "ENV_GROUND",
		3: "ENV_SURFACE",
		4: "ENV_SUBSURFACE",
	}
	VehicleEnvironment_value = map[string]int32{
		"ENV_UNKNOWN":    0,
		"ENV_AIR":        1,
		"ENV_GROUND":     2,
		"ENV_SURFACE":    3,
		"ENV_SUBSURFACE": 4,
	}
)

func (x VehicleEnvironment) Enum() *VehicleEnvironment {
	p := new(VehicleEnvironment)
	*p = x
	return p
}

func (x VehicleEnvironment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleEnvironment) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[1].Descriptor()
}

func (VehicleEnvironment) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[1]
}

func (x VehicleEnvironment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleEnvironment.Descriptor instead.
func (VehicleEnvironment) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{1}
}

type AlertSeverity int32

const (
	AlertSeverity_SEVERITY_INFO     AlertSeverity = 0
	AlertSeverity_SEVERITY_WARNING  AlertSeverity = 1
	AlertSeverity_SEVERITY_ERROR    AlertSeverity = 2
	AlertSeverity_SEVERITY_CRITICAL AlertSeverity = 3
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "SEVERITY_INFO",
		1: "SEVERITY_WARNING",
		2: "SEVERITY_ERROR",
		3: "SEVERITY_CRITICAL",
	}
	AlertSeverity_value = map[string]int32{
		"SEVERITY_INFO":     0,
		"SEVERITY_WARNING":  1,
		"SEVERITY_ERROR":    2,
		"SEVERITY_CRITICAL": 3,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[2].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[2]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{2}
}

type OperationalMode int32

const (
	OperationalMode_MODE_MANUAL     OperationalMode = 0
	OperationalMode_MODE_AUTONOMOUS OperationalMode = 1
	OperationalMode_MODE_GUIDED     OperationalMode = 2
)

// Enum value maps for OperationalMode.
var (
	OperationalMode_name = map[int32]string{
		0: "MODE_MANUAL",
		1: "MODE_AUTONOMOUS",
		2: "MODE_GUIDED",
	}
	OperationalMode_value = map[string]int32{
		"MODE_MANUAL":     0,
		"MODE_AUTONOMOUS": 1,
		"MODE_GUIDED":     2,
	}
)

func (x OperationalMode) Enum() *OperationalMode {
	p := new(OperationalMode)
	*p = x
	return p
}

func (x OperationalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[3].Descriptor()
}

func (OperationalMode) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[3]
}

func (x OperationalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationalMode.Descriptor instead.
func (OperationalMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{3}
}

// Vehicle ack status values.
// NOTE: "timeout" is a gateway-synthetic status (not in this enum) sent when
// the vehicle doesn't respond within OPENC2_CMD_TIMEOUT. See PROTOCOL.md.
type AckStatus int32

const (
	AckStatus_ACK_ACCEPTED  AckStatus = 0
	AckStatus_ACK_REJECTED  AckStatus = 1
	AckStatus_ACK_COMPLETED AckStatus = 2
	AckStatus_ACK_FAILED    AckStatus = 3
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_ACCEPTED",
		1: "ACK_REJECTED",
		2: "ACK_COMPLETED",
		3: "ACK_FAILED",
	}
	AckStatus_value = map[string]int32{
		"ACK_ACCEPTED":  0,
		"ACK_REJECTED":  1,
		"ACK_COMPLETED": 2,
		"ACK_FAILED":    3,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_openc2_proto_enumTypes[4].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_api_proto_openc2_proto_enumTypes[4]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{4}
}

// VehicleMessage is the envelope for all messages from vehicles to gateway.
// The oneof field number acts as the type discriminator in the wire format.
// Gateway unmarshals this first, then switches on which payload is set.
type VehicleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VehicleMessage_Telemetry
	//	*VehicleMessage_Heartbeat
	//	*VehicleMessage_Alert
	//	*VehicleMessage_CommandAck
	Payload       isVehicleMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleMessage) Reset() {
	*x = VehicleMessage{}
	mi := &file_api_proto_openc2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleMessage) ProtoMessage() {}

func (x *VehicleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleMessage.ProtoReflect.Descriptor instead.
func (*VehicleMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleMessage) GetPayload() isVehicleMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VehicleMessage) GetTelemetry() *VehicleTelemetry {
	if x != nil {
		if x, ok := x.Payload.(*VehicleMessage_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *VehicleMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*VehicleMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *VehicleMessage) GetAlert() *Alert {
	if x != nil {
		if x, ok := x.Payload.(*VehicleMessage_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *VehicleMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*VehicleMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

type isVehicleMessage_Payload interface {
	isVehicleMessage_Payload()
}

type VehicleMessage_Telemetry struct {
	Telemetry *VehicleTelemetry `protobuf:"bytes,1,opt,name=telemetry,proto3,oneof"`
}

type VehicleMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type VehicleMessage_Alert struct {
	Alert *Alert `protobuf:"bytes,3,opt,name=alert,proto3,oneof"`
}

type VehicleMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,4,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

func (*VehicleMessage_Telemetry) isVehicleMessage_Payload() {}

func (*VehicleMessage_Heartbeat) isVehicleMessage_Payload() {}

func (*VehicleMessage_Alert) isVehicleMessage_Payload() {}

func (*VehicleMessage_CommandAck) isVehicleMessage_Payload() {}

// VehicleTelemetry is the primary telemetry message sent at high frequency.
// Contains position, velocity, and status information.
//
// NOTE: The `status` field here is for vehicles that include status in every
// telemetry packet. The gateway also tracks status independently based on
// telemetry gaps (see PROTOCOL.md - Offline Detection). Vehicles may omit
// this field if they send separate Heartbeat messages.
//
// TIMESTAMP WARNING: Vehicle clocks are UNTRUSTED (no RTC, no NTP, GPS cold start).
// Use `sequence_num` for ordering, not `timestamp_ms`. The gateway adds its own
// authoritative timestamp (`gts`) when translating to JSON.
type VehicleTelemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique vehicle identifier (e.g., "ugv-husky-07")
	VehicleId string `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	// Unix timestamp in milliseconds - UNTRUSTED, vehicle-local clock
	// Use for display/logging only. See PROTOCOL.md for timestamp semantics.
	TimestampMs int64 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Current position
	Location *Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// Ground speed in meters per second
	SpeedMs float32 `protobuf:"fixed32,4,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"`
	// True heading in degrees [0, 360), 0=North, 90=East
	// NOTE: 360 is normalized to 0. Gateway validates heading < 360.
	HeadingDeg float32 `protobuf:"fixed32,5,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	// Monotonic sequence number for ordering AND deduplication (per-vehicle, wraps at 2^32)
	// Gateway tracks high-water mark per vehicle; seq <= hwm is dropped as duplicate/stale.
	// Use this instead of timestamp for ordering - handles clock skew/reset.
	// See PROTOCOL.md "Gateway Deduplication" for wrap-around handling.
	SequenceNum uint32 `protobuf:"varint,6,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Current operational status (optional - absence means not reported this frame)
	// Use has_status() to check presence. Gateway tracks status independently via telemetry gaps.
	Status *VehicleStatus `protobuf:"varint,7,opt,name=status,proto3,enum=openc2.VehicleStatus,oneof" json:"status,omitempty"`
	// Operating environment
	Environment VehicleEnvironment `protobuf:"varint,8,opt,name=environment,proto3,enum=openc2.VehicleEnvironment" json:"environment,omitempty"`
	// Signal strength (0-5 bars, absence means unknown)
	SignalStrength *uint32 `protobuf:"varint,9,opt,name=signal_strength,json=signalStrength,proto3,oneof" json:"signal_strength,omitempty"`
	// Battery percentage (0-100, absence means unknown)
	BatteryPct    *uint32 `protobuf:"varint,10,opt,name=battery_pct,json=batteryPct,proto3,oneof" json:"battery_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleTelemetry) Reset() {
	*x = VehicleTelemetry{}
	mi := &file_api_proto_openc2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTelemetry) ProtoMessage() {}

func (x *VehicleTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTelemetry.ProtoReflect.Descriptor instead.
func (*VehicleTelemetry) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleTelemetry) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *VehicleTelemetry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *VehicleTelemetry) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *VehicleTelemetry) GetSpeedMs() float32 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

func (x *VehicleTelemetry) GetHeadingDeg() float32 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *VehicleTelemetry) GetSequenceNum() uint32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *VehicleTelemetry) GetStatus() VehicleStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return VehicleStatus_STATUS_ONLINE
}

func (x *VehicleTelemetry) GetEnvironment() VehicleEnvironment {
	if x != nil {
		return x.Environment
	}
	return VehicleEnvironment_ENV_UNKNOWN
}

func (x *VehicleTelemetry) GetSignalStrength() uint32 {
	if x != nil && x.SignalStrength != nil {
		return *x.SignalStrength
	}
	return 0
}

func (x *VehicleTelemetry) GetBatteryPct() uint32 {
	if x != nil && x.BatteryPct != nil {
		return *x.BatteryPct
	}
	return 0
}

// Geographic location in WGS84 coordinates
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude in degrees (-90 to 90)
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude in degrees (-180 to 180)
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Altitude MSL in meters
	AltitudeMslM  float32 `protobuf:"fixed32,3,opt,name=altitude_msl_m,json=altitudeMslM,proto3" json:"altitude_msl_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_api_proto_openc2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAltitudeMslM() float32 {
	if x != nil {
		return x.AltitudeMslM
	}
	return 0
}

// Heartbeat message sent periodically to confirm connectivity
// Note: battery_pct is only in VehicleTelemetry (single source of truth)
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Status        VehicleStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=openc2.VehicleStatus" json:"status,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,4,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_openc2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Heartbeat) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_STATUS_ONLINE
}

func (x *Heartbeat) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

// Alert message for warnings, errors, and events
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Severity      AlertSeverity          `protobuf:"varint,3,opt,name=severity,proto3,enum=openc2.AlertSeverity" json:"severity,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`         // Machine-readable code (e.g., "GEOFENCE_BREACH")
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`   // Human-readable description
	Location      *Location              `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"` // Optional: where the alert occurred
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_api_proto_openc2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{4}
}

func (x *Alert) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Alert) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Alert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_SEVERITY_INFO
}

func (x *Alert) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Command is the envelope for all commands sent to vehicles
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique command ID for tracking acknowledgments
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Target vehicle ID
	VehicleId string `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	// Unix timestamp in milliseconds (UTC)
	TimestampMs int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Command payload (one of the following)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_Goto
	//	*Command_Stop
	//	*Command_ReturnHome
	//	*Command_SetMode
	//	*Command_SetSpeed
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_proto_openc2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Command) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetGoto() *GotoCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Goto); ok {
			return x.Goto
		}
	}
	return nil
}

func (x *Command) GetStop() *StopCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *Command) GetReturnHome() *ReturnHomeCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_ReturnHome); ok {
			return x.ReturnHome
		}
	}
	return nil
}

func (x *Command) GetSetMode() *SetModeCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_SetMode); ok {
			return x.SetMode
		}
	}
	return nil
}

func (x *Command) GetSetSpeed() *SetSpeedCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_SetSpeed); ok {
			return x.SetSpeed
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_Goto struct {
	Goto *GotoCommand `protobuf:"bytes,10,opt,name=goto,proto3,oneof"`
}

type Command_Stop struct {
	Stop *StopCommand `protobuf:"bytes,11,opt,name=stop,proto3,oneof"`
}

type Command_ReturnHome struct {
	ReturnHome *ReturnHomeCommand `protobuf:"bytes,12,opt,name=return_home,json=returnHome,proto3,oneof"`
}

type Command_SetMode struct {
	SetMode *SetModeCommand `protobuf:"bytes,13,opt,name=set_mode,json=setMode,proto3,oneof"`
}

type Command_SetSpeed struct {
	SetSpeed *SetSpeedCommand `protobuf:"bytes,14,opt,name=set_speed,json=setSpeed,proto3,oneof"`
}

func (*Command_Goto) isCommand_Payload() {}

func (*Command_Stop) isCommand_Payload() {}

func (*Command_ReturnHome) isCommand_Payload() {}

func (*Command_SetMode) isCommand_Payload() {}

func (*Command_SetSpeed) isCommand_Payload() {}

// Navigate to a destination
type GotoCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *Location              `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`          // Includes altitude for aerial vehicles
	SpeedMs       float32                `protobuf:"fixed32,2,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"` // Target speed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GotoCommand) Reset() {
	*x = GotoCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GotoCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GotoCommand) ProtoMessage() {}

func (x *GotoCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GotoCommand.ProtoReflect.Descriptor instead.
func (*GotoCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{6}
}

func (x *GotoCommand) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *GotoCommand) GetSpeedMs() float32 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

// Emergency stop
type StopCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCommand) Reset() {
	*x = StopCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCommand) ProtoMessage() {}

func (x *StopCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCommand.ProtoReflect.Descriptor instead.
func (*StopCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{7}
}

// Return to home/launch position
type ReturnHomeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnHomeCommand) Reset() {
	*x = ReturnHomeCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnHomeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnHomeCommand) ProtoMessage() {}

func (x *ReturnHomeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnHomeCommand.ProtoReflect.Descriptor instead.
func (*ReturnHomeCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{8}
}

// Set operational mode
type SetModeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          OperationalMode        `protobuf:"varint,1,opt,name=mode,proto3,enum=openc2.OperationalMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModeCommand) Reset() {
	*x = SetModeCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModeCommand) ProtoMessage() {}

func (x *SetModeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModeCommand.ProtoReflect.Descriptor instead.
func (*SetModeCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{9}
}

func (x *SetModeCommand) GetMode() OperationalMode {
	if x != nil {
		return x.Mode
	}
	return OperationalMode_MODE_MANUAL
}

// Set target speed
type SetSpeedCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeedMs       float32                `protobuf:"fixed32,1,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpeedCommand) Reset() {
	*x = SetSpeedCommand{}
	mi := &file_api_proto_openc2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpeedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpeedCommand) ProtoMessage() {}

func (x *SetSpeedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpeedCommand.ProtoReflect.Descriptor instead.
func (*SetSpeedCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{10}
}

func (x *SetSpeedCommand) GetSpeedMs() float32 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

// GatewayMessage is the envelope for all messages from gateway to vehicles.
// Vehicles receive this on multicast 239.255.0.2:14551, unmarshal, and switch
// on which payload is set. Commands are filtered by vehicle_id; heartbeats
// are processed by all vehicles.
type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayMessage_Command
	//	*GatewayMessage_Heartbeat
	Payload       isGatewayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_api_proto_openc2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{11}
}

func (x *GatewayMessage) GetPayload() isGatewayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *GatewayMessage) GetHeartbeat() *GatewayHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isGatewayMessage_Payload interface {
	isGatewayMessage_Payload()
}

type GatewayMessage_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type GatewayMessage_Heartbeat struct {
	Heartbeat *GatewayHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*GatewayMessage_Command) isGatewayMessage_Payload() {}

func (*GatewayMessage_Heartbeat) isGatewayMessage_Payload() {}

// GatewayHeartbeat is sent periodically (every 1s) to let vehicles detect
// gateway connectivity loss. If a vehicle doesn't receive a heartbeat for
// OPENC2_GATEWAY_TIMEOUT (default 5s), it MUST trigger failsafe behavior.
//
// Failsafe modes (configured via OPENC2_FAILSAFE_MODE):
//   - RTL: Return to home/launch position (default for aerial)
//   - HOLD: Stop and hold current position (default for ground)
//   - CONTINUE: Continue autonomous mission
//   - LAND: Immediate landing (aerial only)
//
// See PROTOCOL.md "Gateway Loss Detection" for full behavioral specification.
//
// Vehicles SHOULD NOT use this for time sync - gateway clock is authoritative
// for the UI, but vehicles should rely on GPS/internal clocks for autonomy.
type GatewayHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix timestamp in milliseconds (UTC) - gateway's authoritative clock
	TimestampMs int64 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Monotonic sequence number for ordering/loss detection (wraps at 2^32)
	// Vehicles can detect packet loss by tracking gaps in sequence.
	SequenceNum uint32 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	// Number of currently connected UI clients (informational)
	ConnectedClients uint32 `protobuf:"varint,3,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	// Number of vehicles in registry (informational)
	TrackedVehicles uint32 `protobuf:"varint,4,opt,name=tracked_vehicles,json=trackedVehicles,proto3" json:"tracked_vehicles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GatewayHeartbeat) Reset() {
	*x = GatewayHeartbeat{}
	mi := &file_api_proto_openc2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHeartbeat) ProtoMessage() {}

func (x *GatewayHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHeartbeat.ProtoReflect.Descriptor instead.
func (*GatewayHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{12}
}

func (x *GatewayHeartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *GatewayHeartbeat) GetSequenceNum() uint32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *GatewayHeartbeat) GetConnectedClients() uint32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *GatewayHeartbeat) GetTrackedVehicles() uint32 {
	if x != nil {
		return x.TrackedVehicles
	}
	return 0
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	VehicleId     string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Status        AckStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=openc2.AckStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // Human-readable status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_api_proto_openc2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_openc2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_api_proto_openc2_proto_rawDescGZIP(), []int{13}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *CommandAck) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *CommandAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_ACCEPTED
}

func (x *CommandAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_openc2_proto protoreflect.FileDescriptor

const file_api_proto_openc2_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/openc2.proto\x12\x06openc2\"\xe6\x01\n" +
	"\x0eVehicleMessage\x128\n" +
	"\ttelemetry\x18\x01 \x01(\v2\x18.openc2.VehicleTelemetryH\x00R\ttelemetry\x121\n" +
	"\theartbeat\x18\x02 \x01(\v2\x11.openc2.HeartbeatH\x00R\theartbeat\x12%\n" +
	"\x05alert\x18\x03 \x01(\v2\r.openc2.AlertH\x00R\x05alert\x125\n" +
	"\vcommand_ack\x18\x04 \x01(\v2\x12.openc2.CommandAckH\x00R\n" +
	"commandAckB\t\n" +
	"\apayload\"\xd6\x03\n" +
	"\x10VehicleTelemetry\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12,\n" +
	"\blocation\x18\x03 \x01(\v2\x10.openc2.LocationR\blocation\x12\x19\n" +
	"\bspeed_ms\x18\x04 \x01(\x02R\aspeedMs\x12\x1f\n" +
	"\vheading_deg\x18\x05 \x01(\x02R\n" +
	"headingDeg\x12!\n" +
	"\fsequence_num\x18\x06 \x01(\rR\vsequenceNum\x122\n" +
	"\x06status\x18\a \x01(\x0e2\x15.openc2.VehicleStatusH\x00R\x06status\x88\x01\x01\x12<\n" +
	"\venvironment\x18\b \x01(\x0e2\x1a.openc2.VehicleEnvironmentR\venvironment\x12,\n" +
	"\x0fsignal_strength\x18\t \x01(\rH\x01R\x0esignalStrength\x88\x01\x01\x12$\n" +
	"\vbattery_pct\x18\n" +
	" \x01(\rH\x02R\n" +
	"batteryPct\x88\x01\x01B\t\n" +
	"\a_statusB\x12\n" +
	"\x10_signal_strengthB\x0e\n" +
	"\f_battery_pct\"j\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12$\n" +
	"\x0ealtitude_msl_m\x18\x03 \x01(\x02R\faltitudeMslM\"\x99\x01\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.openc2.VehicleStatusR\x06status\x12\x1b\n" +
	"\tuptime_ms\x18\x04 \x01(\x03R\buptimeMs\"\xd8\x01\n" +
	"\x05Alert\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x121\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x15.openc2.AlertSeverityR\bseverity\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12,\n" +
	"\blocation\x18\x06 \x01(\v2\x10.openc2.LocationR\blocation\"\xf6\x02\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12)\n" +
	"\x04goto\x18\n" +
	" \x01(\v2\x13.openc2.GotoCommandH\x00R\x04goto\x12)\n" +
	"\x04stop\x18\v \x01(\v2\x13.openc2.StopCommandH\x00R\x04stop\x12<\n" +
	"\vreturn_home\x18\f \x01(\v2\x19.openc2.ReturnHomeCommandH\x00R\n" +
	"returnHome\x123\n" +
	"\bset_mode\x18\r \x01(\v2\x16.openc2.SetModeCommandH\x00R\asetMode\x126\n" +
	"\tset_speed\x18\x0e \x01(\v2\x17.openc2.SetSpeedCommandH\x00R\bsetSpeedB\t\n" +
	"\apayload\"\\\n" +
	"\vGotoCommand\x122\n" +
	"\vdestination\x18\x01 \x01(\v2\x10.openc2.LocationR\vdestination\x12\x19\n" +
	"\bspeed_ms\x18\x02 \x01(\x02R\aspeedMs\"\r\n" +
	"\vStopCommand\"\x13\n" +
	"\x11ReturnHomeCommand\"=\n" +
	"\x0eSetModeCommand\x12+\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x17.openc2.OperationalModeR\x04mode\",\n" +
	"\x0fSetSpeedCommand\x12\x19\n" +
	"\bspeed_ms\x18\x01 \x01(\x02R\aspeedMs\"\x82\x01\n" +
	"\x0eGatewayMessage\x12+\n" +
	"\acommand\x18\x01 \x01(\v2\x0f.openc2.CommandH\x00R\acommand\x128\n" +
	"\theartbeat\x18\x02 \x01(\v2\x18.openc2.GatewayHeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xb0\x01\n" +
	"\x10GatewayHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\rR\vsequenceNum\x12+\n" +
	"\x11connected_clients\x18\x03 \x01(\rR\x10connectedClients\x12)\n" +
	"\x10tracked_vehicles\x18\x04 \x01(\rR\x0ftrackedVehicles\"\xb2\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.openc2.AckStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*J\n" +
	"\rVehicleStatus\x12\x11\n" +
	"\rSTATUS_ONLINE\x10\x00\x12\x12\n" +
	"\x0eSTATUS_OFFLINE\x10\x01\x12\x12\n" +
	"\x0eSTATUS_STANDBY\x10\x02*g\n" +
	"\x12VehicleEnvironment\x12\x0f\n" +
	"\vENV_UNKNOWN\x10\x00\x12\v\n" +
	"\aENV_AIR\x10\x01\x12\x0e\n" +
	"\n" +
	"ENV_GROUND\x10\x02\x12\x0f\n" +
	"\vENV_SURFACE\x10\x03\x12\x12\n" +
	"\x0eENV_SUBSURFACE\x10\x04*c\n" +
	"\rAlertSeverity\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x00\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x01\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x02\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x03*H\n" +
	"\x0fOperationalMode\x12\x0f\n" +
	"\vMODE_MANUAL\x10\x00\x12\x13\n" +
	"\x0fMODE_AUTONOMOUS\x10\x01\x12\x0f\n" +
	"\vMODE_GUIDED\x10\x02*R\n" +
	"\tAckStatus\x12\x10\n" +
	"\fACK_ACCEPTED\x10\x00\x12\x10\n" +
	"\fACK_REJECTED\x10\x01\x12\x11\n" +
	"\rACK_COMPLETED\x10\x02\x12\x0e\n" +
	"\n" +
	"ACK_FAILED\x10\x03B0Z.github.com/EthanMBoos/openc2-gateway/api/protob\x06proto3"

var (
	file_api_proto_openc2_proto_rawDescOnce sync.Once
	file_api_proto_openc2_proto_rawDescData []byte
)

func file_api_proto_openc2_proto_rawDescGZIP() []byte {
	file_api_proto_openc2_proto_rawDescOnce.Do(func() {
		file_api_proto_openc2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_openc2_proto_rawDesc), len(file_api_proto_openc2_proto_rawDesc)))
	})
	return file_api_proto_openc2_proto_rawDescData
}

var file_api_proto_openc2_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_proto_openc2_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_openc2_proto_goTypes = []any{
	(VehicleStatus)(0),        // 0: openc2.VehicleStatus
	(VehicleEnvironment)(0),   // 1: openc2.VehicleEnvironment
	(AlertSeverity)(0),        // 2: openc2.AlertSeverity
	(OperationalMode)(0),      // 3: openc2.OperationalMode
	(AckStatus)(0),            // 4: openc2.AckStatus
	(*VehicleMessage)(nil),    // 5: openc2.VehicleMessage
	(*VehicleTelemetry)(nil),  // 6: openc2.VehicleTelemetry
	(*Location)(nil),          // 7: openc2.Location
	(*Heartbeat)(nil),         // 8: openc2.Heartbeat
	(*Alert)(nil),             // 9: openc2.Alert
	(*Command)(nil),           // 10: openc2.Command
	(*GotoCommand)(nil),       // 11: openc2.GotoCommand
	(*StopCommand)(nil),       // 12: openc2.StopCommand
	(*ReturnHomeCommand)(nil), // 13: openc2.ReturnHomeCommand
	(*SetModeCommand)(nil),    // 14: openc2.SetModeCommand
	(*SetSpeedCommand)(nil),   // 15: openc2.SetSpeedCommand
	(*GatewayMessage)(nil),    // 16: openc2.GatewayMessage
	(*GatewayHeartbeat)(nil),  // 17: openc2.GatewayHeartbeat
	(*CommandAck)(nil),        // 18: openc2.CommandAck
}
var file_api_proto_openc2_proto_depIdxs = []int32{
	6,  // 0: openc2.VehicleMessage.telemetry:type_name -> openc2.VehicleTelemetry
	8,  // 1: openc2.VehicleMessage.heartbeat:type_name -> openc2.Heartbeat
	9,  // 2: openc2.VehicleMessage.alert:type_name -> openc2.Alert
	18, // 3: openc2.VehicleMessage.command_ack:type_name -> openc2.CommandAck
	7,  // 4: openc2.VehicleTelemetry.location:type_name -> openc2.Location
	0,  // 5: openc2.VehicleTelemetry.status:type_name -> openc2.VehicleStatus
	1,  // 6: openc2.VehicleTelemetry.environment:type_name -> openc2.VehicleEnvironment
	0,  // 7: openc2.Heartbeat.status:type_name -> openc2.VehicleStatus
	2,  // 8: openc2.Alert.severity:type_name -> openc2.AlertSeverity
	7,  // 9: openc2.Alert.location:type_name -> openc2.Location
	11, // 10: openc2.Command.goto:type_name -> openc2.GotoCommand
	12, // 11: openc2.Command.stop:type_name -> openc2.StopCommand
	13, // 12: openc2.Command.return_home:type_name -> openc2.ReturnHomeCommand
	14, // 13: openc2.Command.set_mode:type_name -> openc2.SetModeCommand
	15, // 14: openc2.Command.set_speed:type_name -> openc2.SetSpeedCommand
	7,  // 15: openc2.GotoCommand.destination:type_name -> openc2.Location
	3,  // 16: openc2.SetModeCommand.mode:type_name -> openc2.OperationalMode
	10, // 17: openc2.GatewayMessage.command:type_name -> openc2.Command
	17, // 18: openc2.GatewayMessage.heartbeat:type_name -> openc2.GatewayHeartbeat
	4,  // 19: openc2.CommandAck.status:type_name -> openc2.AckStatus
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_api_proto_openc2_proto_init() }
func file_api_proto_openc2_proto_init() {
	if File_api_proto_openc2_proto != nil {
		return
	}
	file_api_proto_openc2_proto_msgTypes[0].OneofWrappers = []any{
		(*VehicleMessage_Telemetry)(nil),
		(*VehicleMessage_Heartbeat)(nil),
		(*VehicleMessage_Alert)(nil),
		(*VehicleMessage_CommandAck)(nil),
	}
	file_api_proto_openc2_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_openc2_proto_msgTypes[5].OneofWrappers = []any{
		(*Command_Goto)(nil),
		(*Command_Stop)(nil),
		(*Command_ReturnHome)(nil),
		(*Command_SetMode)(nil),
		(*Command_SetSpeed)(nil),
	}
	file_api_proto_openc2_proto_msgTypes[11].OneofWrappers = []any{
		(*GatewayMessage_Command)(nil),
		(*GatewayMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_openc2_proto_rawDesc), len(file_api_proto_openc2_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_openc2_proto_goTypes,
		DependencyIndexes: file_api_proto_openc2_proto_depIdxs,
		EnumInfos:         file_api_proto_openc2_proto_enumTypes,
		MessageInfos:      file_api_proto_openc2_proto_msgTypes,
	}.Build()
	File_api_proto_openc2_proto = out.File
	file_api_proto_openc2_proto_goTypes = nil
	file_api_proto_openc2_proto_depIdxs = nil
}
