// BlueBoat USV Extension Protocol
//
// Extension telemetry and command definitions for BlueRobotics BlueBoat USV.
// This is an extension proto — payloads are carried inside openc2.ExtensionData.
//
// See docs/EXTENSIBILITY.md for extension architecture.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: internal/extensions/blueboat/blueboat.proto

package blueboat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NavMode represents the boat's current navigation mode.
type NavMode int32

const (
	NavMode_NAV_MODE_UNKNOWN     NavMode = 0
	NavMode_NAV_MODE_MANUAL      NavMode = 1 // Direct RC/teleop control
	NavMode_NAV_MODE_HOLD        NavMode = 2 // Station keeping (hold position)
	NavMode_NAV_MODE_WAYPOINT    NavMode = 3 // Autonomous waypoint navigation
	NavMode_NAV_MODE_SURVEY      NavMode = 4 // Survey pattern (lawn mower)
	NavMode_NAV_MODE_RETURN_HOME NavMode = 5 // Returning to dock/home
	NavMode_NAV_MODE_LOITER      NavMode = 6 // Circling at location
	NavMode_NAV_MODE_DOCKING     NavMode = 7 // Autonomous docking sequence
)

// Enum value maps for NavMode.
var (
	NavMode_name = map[int32]string{
		0: "NAV_MODE_UNKNOWN",
		1: "NAV_MODE_MANUAL",
		2: "NAV_MODE_HOLD",
		3: "NAV_MODE_WAYPOINT",
		4: "NAV_MODE_SURVEY",
		5: "NAV_MODE_RETURN_HOME",
		6: "NAV_MODE_LOITER",
		7: "NAV_MODE_DOCKING",
	}
	NavMode_value = map[string]int32{
		"NAV_MODE_UNKNOWN":     0,
		"NAV_MODE_MANUAL":      1,
		"NAV_MODE_HOLD":        2,
		"NAV_MODE_WAYPOINT":    3,
		"NAV_MODE_SURVEY":      4,
		"NAV_MODE_RETURN_HOME": 5,
		"NAV_MODE_LOITER":      6,
		"NAV_MODE_DOCKING":     7,
	}
)

func (x NavMode) Enum() *NavMode {
	p := new(NavMode)
	*p = x
	return p
}

func (x NavMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NavMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_extensions_blueboat_blueboat_proto_enumTypes[0].Descriptor()
}

func (NavMode) Type() protoreflect.EnumType {
	return &file_internal_extensions_blueboat_blueboat_proto_enumTypes[0]
}

func (x NavMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NavMode.Descriptor instead.
func (NavMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP(), []int{0}
}

// BlueboatTelemetry contains BlueBoat-specific state sent in VehicleTelemetry.extensions["blueboat"].
type BlueboatTelemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current navigation mode
	NavMode NavMode `protobuf:"varint,1,opt,name=nav_mode,json=navMode,proto3,enum=blueboat.NavMode" json:"nav_mode,omitempty"`
	// Water depth below hull in meters (from sonar/depth sensor)
	WaterDepthM float32 `protobuf:"fixed32,2,opt,name=water_depth_m,json=waterDepthM,proto3" json:"water_depth_m,omitempty"`
	// Battery state
	Battery *BatteryState `protobuf:"bytes,3,opt,name=battery,proto3" json:"battery,omitempty"`
	// Thruster status (dual thruster configuration)
	Thrusters *ThrusterStatus `protobuf:"bytes,4,opt,name=thrusters,proto3" json:"thrusters,omitempty"`
	// GPS fix quality (0-5, 5 = RTK fix)
	GpsFixQuality uint32 `protobuf:"varint,5,opt,name=gps_fix_quality,json=gpsFixQuality,proto3" json:"gps_fix_quality,omitempty"`
	// Number of satellites tracked
	Satellites uint32 `protobuf:"varint,6,opt,name=satellites,proto3" json:"satellites,omitempty"`
	// Current draw total in Amps
	CurrentDrawA float32 `protobuf:"fixed32,7,opt,name=current_draw_a,json=currentDrawA,proto3" json:"current_draw_a,omitempty"`
	// Estimated range remaining in meters
	RangeRemainingM float32 `protobuf:"fixed32,8,opt,name=range_remaining_m,json=rangeRemainingM,proto3" json:"range_remaining_m,omitempty"`
	// Wind speed from onboard anemometer in m/s
	WindSpeedMs float32 `protobuf:"fixed32,9,opt,name=wind_speed_ms,json=windSpeedMs,proto3" json:"wind_speed_ms,omitempty"`
	// Home/dock location
	Dock          *DockLocation `protobuf:"bytes,10,opt,name=dock,proto3" json:"dock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlueboatTelemetry) Reset() {
	*x = BlueboatTelemetry{}
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlueboatTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueboatTelemetry) ProtoMessage() {}

func (x *BlueboatTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueboatTelemetry.ProtoReflect.Descriptor instead.
func (*BlueboatTelemetry) Descriptor() ([]byte, []int) {
	return file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP(), []int{0}
}

func (x *BlueboatTelemetry) GetNavMode() NavMode {
	if x != nil {
		return x.NavMode
	}
	return NavMode_NAV_MODE_UNKNOWN
}

func (x *BlueboatTelemetry) GetWaterDepthM() float32 {
	if x != nil {
		return x.WaterDepthM
	}
	return 0
}

func (x *BlueboatTelemetry) GetBattery() *BatteryState {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *BlueboatTelemetry) GetThrusters() *ThrusterStatus {
	if x != nil {
		return x.Thrusters
	}
	return nil
}

func (x *BlueboatTelemetry) GetGpsFixQuality() uint32 {
	if x != nil {
		return x.GpsFixQuality
	}
	return 0
}

func (x *BlueboatTelemetry) GetSatellites() uint32 {
	if x != nil {
		return x.Satellites
	}
	return 0
}

func (x *BlueboatTelemetry) GetCurrentDrawA() float32 {
	if x != nil {
		return x.CurrentDrawA
	}
	return 0
}

func (x *BlueboatTelemetry) GetRangeRemainingM() float32 {
	if x != nil {
		return x.RangeRemainingM
	}
	return 0
}

func (x *BlueboatTelemetry) GetWindSpeedMs() float32 {
	if x != nil {
		return x.WindSpeedMs
	}
	return 0
}

func (x *BlueboatTelemetry) GetDock() *DockLocation {
	if x != nil {
		return x.Dock
	}
	return nil
}

// BatteryState reports battery pack status.
type BatteryState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voltage       float32                `protobuf:"fixed32,1,opt,name=voltage,proto3" json:"voltage,omitempty"`          // Pack voltage
	Percentage    float32                `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`    // State of charge 0-100
	TempC         float32                `protobuf:"fixed32,3,opt,name=temp_c,json=tempC,proto3" json:"temp_c,omitempty"` // Battery temperature
	Cycles        uint32                 `protobuf:"varint,4,opt,name=cycles,proto3" json:"cycles,omitempty"`             // Charge cycles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryState) Reset() {
	*x = BatteryState{}
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryState) ProtoMessage() {}

func (x *BatteryState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryState.ProtoReflect.Descriptor instead.
func (*BatteryState) Descriptor() ([]byte, []int) {
	return file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP(), []int{1}
}

func (x *BatteryState) GetVoltage() float32 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *BatteryState) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *BatteryState) GetTempC() float32 {
	if x != nil {
		return x.TempC
	}
	return 0
}

func (x *BatteryState) GetCycles() uint32 {
	if x != nil {
		return x.Cycles
	}
	return 0
}

// ThrusterStatus reports dual thruster health.
type ThrusterStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftRpm       float32                `protobuf:"fixed32,1,opt,name=left_rpm,json=leftRpm,proto3" json:"left_rpm,omitempty"`            // Left thruster RPM
	RightRpm      float32                `protobuf:"fixed32,2,opt,name=right_rpm,json=rightRpm,proto3" json:"right_rpm,omitempty"`         // Right thruster RPM
	LeftTempC     float32                `protobuf:"fixed32,3,opt,name=left_temp_c,json=leftTempC,proto3" json:"left_temp_c,omitempty"`    // Left thruster motor temp
	RightTempC    float32                `protobuf:"fixed32,4,opt,name=right_temp_c,json=rightTempC,proto3" json:"right_temp_c,omitempty"` // Right thruster motor temp
	LeftFault     bool                   `protobuf:"varint,5,opt,name=left_fault,json=leftFault,proto3" json:"left_fault,omitempty"`       // Left thruster fault
	RightFault    bool                   `protobuf:"varint,6,opt,name=right_fault,json=rightFault,proto3" json:"right_fault,omitempty"`    // Right thruster fault
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrusterStatus) Reset() {
	*x = ThrusterStatus{}
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrusterStatus) ProtoMessage() {}

func (x *ThrusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrusterStatus.ProtoReflect.Descriptor instead.
func (*ThrusterStatus) Descriptor() ([]byte, []int) {
	return file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP(), []int{2}
}

func (x *ThrusterStatus) GetLeftRpm() float32 {
	if x != nil {
		return x.LeftRpm
	}
	return 0
}

func (x *ThrusterStatus) GetRightRpm() float32 {
	if x != nil {
		return x.RightRpm
	}
	return 0
}

func (x *ThrusterStatus) GetLeftTempC() float32 {
	if x != nil {
		return x.LeftTempC
	}
	return 0
}

func (x *ThrusterStatus) GetRightTempC() float32 {
	if x != nil {
		return x.RightTempC
	}
	return 0
}

func (x *ThrusterStatus) GetLeftFault() bool {
	if x != nil {
		return x.LeftFault
	}
	return false
}

func (x *ThrusterStatus) GetRightFault() bool {
	if x != nil {
		return x.RightFault
	}
	return false
}

// DockLocation is where the boat will return on RTH.
type DockLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockLocation) Reset() {
	*x = DockLocation{}
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockLocation) ProtoMessage() {}

func (x *DockLocation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockLocation.ProtoReflect.Descriptor instead.
func (*DockLocation) Descriptor() ([]byte, []int) {
	return file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP(), []int{3}
}

func (x *DockLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DockLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// SetNavModeCommand changes the navigation mode.
type SetNavModeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          NavMode                `protobuf:"varint,1,opt,name=mode,proto3,enum=blueboat.NavMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNavModeCommand) Reset() {
	*x = SetNavModeCommand{}
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNavModeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNavModeCommand) ProtoMessage() {}

func (x *SetNavModeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNavModeCommand.ProtoReflect.Descriptor instead.
func (*SetNavModeCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP(), []int{4}
}

func (x *SetNavModeCommand) GetMode() NavMode {
	if x != nil {
		return x.Mode
	}
	return NavMode_NAV_MODE_UNKNOWN
}

// StartSurveyCommand begins a survey pattern over a search zone.
type StartSurveyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`                       // Reference to searchZone on map
	LaneSpacingM  float32                `protobuf:"fixed32,2,opt,name=lane_spacing_m,json=laneSpacingM,proto3" json:"lane_spacing_m,omitempty"` // Distance between survey lanes
	SpeedMs       float32                `protobuf:"fixed32,3,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"`                  // Survey speed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSurveyCommand) Reset() {
	*x = StartSurveyCommand{}
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSurveyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSurveyCommand) ProtoMessage() {}

func (x *StartSurveyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSurveyCommand.ProtoReflect.Descriptor instead.
func (*StartSurveyCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP(), []int{5}
}

func (x *StartSurveyCommand) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *StartSurveyCommand) GetLaneSpacingM() float32 {
	if x != nil {
		return x.LaneSpacingM
	}
	return 0
}

func (x *StartSurveyCommand) GetSpeedMs() float32 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

// SetDockCommand sets the home/dock location.
type SetDockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDockCommand) Reset() {
	*x = SetDockCommand{}
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDockCommand) ProtoMessage() {}

func (x *SetDockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_blueboat_blueboat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDockCommand.ProtoReflect.Descriptor instead.
func (*SetDockCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP(), []int{6}
}

func (x *SetDockCommand) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SetDockCommand) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_internal_extensions_blueboat_blueboat_proto protoreflect.FileDescriptor

const file_internal_extensions_blueboat_blueboat_proto_rawDesc = "" +
	"\n" +
	"+internal/extensions/blueboat/blueboat.proto\x12\bblueboat\"\xb9\x03\n" +
	"\x11BlueboatTelemetry\x12,\n" +
	"\bnav_mode\x18\x01 \x01(\x0e2\x11.blueboat.NavModeR\anavMode\x12\"\n" +
	"\rwater_depth_m\x18\x02 \x01(\x02R\vwaterDepthM\x120\n" +
	"\abattery\x18\x03 \x01(\v2\x16.blueboat.BatteryStateR\abattery\x126\n" +
	"\tthrusters\x18\x04 \x01(\v2\x18.blueboat.ThrusterStatusR\tthrusters\x12&\n" +
	"\x0fgps_fix_quality\x18\x05 \x01(\rR\rgpsFixQuality\x12\x1e\n" +
	"\n" +
	"satellites\x18\x06 \x01(\rR\n" +
	"satellites\x12$\n" +
	"\x0ecurrent_draw_a\x18\a \x01(\x02R\fcurrentDrawA\x12*\n" +
	"\x11range_remaining_m\x18\b \x01(\x02R\x0frangeRemainingM\x12\"\n" +
	"\rwind_speed_ms\x18\t \x01(\x02R\vwindSpeedMs\x12*\n" +
	"\x04dock\x18\n" +
	" \x01(\v2\x16.blueboat.DockLocationR\x04dock\"w\n" +
	"\fBatteryState\x12\x18\n" +
	"\avoltage\x18\x01 \x01(\x02R\avoltage\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x02R\n" +
	"percentage\x12\x15\n" +
	"\x06temp_c\x18\x03 \x01(\x02R\x05tempC\x12\x16\n" +
	"\x06cycles\x18\x04 \x01(\rR\x06cycles\"\xca\x01\n" +
	"\x0eThrusterStatus\x12\x19\n" +
	"\bleft_rpm\x18\x01 \x01(\x02R\aleftRpm\x12\x1b\n" +
	"\tright_rpm\x18\x02 \x01(\x02R\brightRpm\x12\x1e\n" +
	"\vleft_temp_c\x18\x03 \x01(\x02R\tleftTempC\x12 \n" +
	"\fright_temp_c\x18\x04 \x01(\x02R\n" +
	"rightTempC\x12\x1d\n" +
	"\n" +
	"left_fault\x18\x05 \x01(\bR\tleftFault\x12\x1f\n" +
	"\vright_fault\x18\x06 \x01(\bR\n" +
	"rightFault\"H\n" +
	"\fDockLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\":\n" +
	"\x11SetNavModeCommand\x12%\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x11.blueboat.NavModeR\x04mode\"n\n" +
	"\x12StartSurveyCommand\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12$\n" +
	"\x0elane_spacing_m\x18\x02 \x01(\x02R\flaneSpacingM\x12\x19\n" +
	"\bspeed_ms\x18\x03 \x01(\x02R\aspeedMs\"J\n" +
	"\x0eSetDockCommand\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude*\xb8\x01\n" +
	"\aNavMode\x12\x14\n" +
	"\x10NAV_MODE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fNAV_MODE_MANUAL\x10\x01\x12\x11\n" +
	"\rNAV_MODE_HOLD\x10\x02\x12\x15\n" +
	"\x11NAV_MODE_WAYPOINT\x10\x03\x12\x13\n" +
	"\x0fNAV_MODE_SURVEY\x10\x04\x12\x18\n" +
	"\x14NAV_MODE_RETURN_HOME\x10\x05\x12\x13\n" +
	"\x0fNAV_MODE_LOITER\x10\x06\x12\x14\n" +
	"\x10NAV_MODE_DOCKING\x10\aBCZAgithub.com/EthanMBoos/openc2-gateway/internal/extensions/blueboatb\x06proto3"

var (
	file_internal_extensions_blueboat_blueboat_proto_rawDescOnce sync.Once
	file_internal_extensions_blueboat_blueboat_proto_rawDescData []byte
)

func file_internal_extensions_blueboat_blueboat_proto_rawDescGZIP() []byte {
	file_internal_extensions_blueboat_blueboat_proto_rawDescOnce.Do(func() {
		file_internal_extensions_blueboat_blueboat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_extensions_blueboat_blueboat_proto_rawDesc), len(file_internal_extensions_blueboat_blueboat_proto_rawDesc)))
	})
	return file_internal_extensions_blueboat_blueboat_proto_rawDescData
}

var file_internal_extensions_blueboat_blueboat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_extensions_blueboat_blueboat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_extensions_blueboat_blueboat_proto_goTypes = []any{
	(NavMode)(0),               // 0: blueboat.NavMode
	(*BlueboatTelemetry)(nil),  // 1: blueboat.BlueboatTelemetry
	(*BatteryState)(nil),       // 2: blueboat.BatteryState
	(*ThrusterStatus)(nil),     // 3: blueboat.ThrusterStatus
	(*DockLocation)(nil),       // 4: blueboat.DockLocation
	(*SetNavModeCommand)(nil),  // 5: blueboat.SetNavModeCommand
	(*StartSurveyCommand)(nil), // 6: blueboat.StartSurveyCommand
	(*SetDockCommand)(nil),     // 7: blueboat.SetDockCommand
}
var file_internal_extensions_blueboat_blueboat_proto_depIdxs = []int32{
	0, // 0: blueboat.BlueboatTelemetry.nav_mode:type_name -> blueboat.NavMode
	2, // 1: blueboat.BlueboatTelemetry.battery:type_name -> blueboat.BatteryState
	3, // 2: blueboat.BlueboatTelemetry.thrusters:type_name -> blueboat.ThrusterStatus
	4, // 3: blueboat.BlueboatTelemetry.dock:type_name -> blueboat.DockLocation
	0, // 4: blueboat.SetNavModeCommand.mode:type_name -> blueboat.NavMode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_extensions_blueboat_blueboat_proto_init() }
func file_internal_extensions_blueboat_blueboat_proto_init() {
	if File_internal_extensions_blueboat_blueboat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_extensions_blueboat_blueboat_proto_rawDesc), len(file_internal_extensions_blueboat_blueboat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_extensions_blueboat_blueboat_proto_goTypes,
		DependencyIndexes: file_internal_extensions_blueboat_blueboat_proto_depIdxs,
		EnumInfos:         file_internal_extensions_blueboat_blueboat_proto_enumTypes,
		MessageInfos:      file_internal_extensions_blueboat_blueboat_proto_msgTypes,
	}.Build()
	File_internal_extensions_blueboat_blueboat_proto = out.File
	file_internal_extensions_blueboat_blueboat_proto_goTypes = nil
	file_internal_extensions_blueboat_blueboat_proto_depIdxs = nil
}
