// Skydio UAV Extension Protocol
//
// Extension telemetry and command definitions for Skydio autonomous drones.
// This is an extension proto — payloads are carried inside pidgin.ExtensionData.
//
// See docs/EXTENSIBILITY.md for extension architecture.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/extensions/skydio/skydio.proto

package skydio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FlightMode represents the drone's current flight behavior.
type FlightMode int32

const (
	FlightMode_FLIGHT_MODE_UNKNOWN     FlightMode = 0
	FlightMode_FLIGHT_MODE_IDLE        FlightMode = 1  // Motors off, on ground
	FlightMode_FLIGHT_MODE_HOVER       FlightMode = 2  // Stationary hover
	FlightMode_FLIGHT_MODE_MANUAL      FlightMode = 3  // Direct pilot control
	FlightMode_FLIGHT_MODE_WAYPOINT    FlightMode = 4  // Flying to waypoint
	FlightMode_FLIGHT_MODE_ORBIT       FlightMode = 5  // Orbiting a point of interest
	FlightMode_FLIGHT_MODE_TRACK       FlightMode = 6  // Autonomous subject tracking
	FlightMode_FLIGHT_MODE_CABLE_CAM   FlightMode = 7  // Virtual cable cam path
	FlightMode_FLIGHT_MODE_RETURN_HOME FlightMode = 8  // Returning to home location
	FlightMode_FLIGHT_MODE_LANDING     FlightMode = 9  // Landing sequence
	FlightMode_FLIGHT_MODE_EMERGENCY   FlightMode = 10 // Emergency descent
)

// Enum value maps for FlightMode.
var (
	FlightMode_name = map[int32]string{
		0:  "FLIGHT_MODE_UNKNOWN",
		1:  "FLIGHT_MODE_IDLE",
		2:  "FLIGHT_MODE_HOVER",
		3:  "FLIGHT_MODE_MANUAL",
		4:  "FLIGHT_MODE_WAYPOINT",
		5:  "FLIGHT_MODE_ORBIT",
		6:  "FLIGHT_MODE_TRACK",
		7:  "FLIGHT_MODE_CABLE_CAM",
		8:  "FLIGHT_MODE_RETURN_HOME",
		9:  "FLIGHT_MODE_LANDING",
		10: "FLIGHT_MODE_EMERGENCY",
	}
	FlightMode_value = map[string]int32{
		"FLIGHT_MODE_UNKNOWN":     0,
		"FLIGHT_MODE_IDLE":        1,
		"FLIGHT_MODE_HOVER":       2,
		"FLIGHT_MODE_MANUAL":      3,
		"FLIGHT_MODE_WAYPOINT":    4,
		"FLIGHT_MODE_ORBIT":       5,
		"FLIGHT_MODE_TRACK":       6,
		"FLIGHT_MODE_CABLE_CAM":   7,
		"FLIGHT_MODE_RETURN_HOME": 8,
		"FLIGHT_MODE_LANDING":     9,
		"FLIGHT_MODE_EMERGENCY":   10,
	}
)

func (x FlightMode) Enum() *FlightMode {
	p := new(FlightMode)
	*p = x
	return p
}

func (x FlightMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlightMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_extensions_skydio_skydio_proto_enumTypes[0].Descriptor()
}

func (FlightMode) Type() protoreflect.EnumType {
	return &file_internal_extensions_skydio_skydio_proto_enumTypes[0]
}

func (x FlightMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlightMode.Descriptor instead.
func (FlightMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{0}
}

// SkydioTelemetry contains Skydio-specific state sent in VehicleTelemetry.extensions["skydio"].
type SkydioTelemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current flight mode
	FlightMode FlightMode `protobuf:"varint,1,opt,name=flight_mode,json=flightMode,proto3,enum=skydio.FlightMode" json:"flight_mode,omitempty"`
	// GPS fix quality (0-5, 5 = RTK fix)
	GpsFixQuality uint32 `protobuf:"varint,2,opt,name=gps_fix_quality,json=gpsFixQuality,proto3" json:"gps_fix_quality,omitempty"`
	// Number of satellites tracked
	Satellites uint32 `protobuf:"varint,3,opt,name=satellites,proto3" json:"satellites,omitempty"`
	// Gimbal orientation
	Gimbal *GimbalState `protobuf:"bytes,4,opt,name=gimbal,proto3" json:"gimbal,omitempty"`
	// Obstacle avoidance status
	ObstacleAvoidance *ObstacleAvoidance `protobuf:"bytes,5,opt,name=obstacle_avoidance,json=obstacleAvoidance,proto3" json:"obstacle_avoidance,omitempty"`
	// Recording state
	Recording *RecordingState `protobuf:"bytes,6,opt,name=recording,proto3" json:"recording,omitempty"`
	// Wind estimate in m/s
	WindSpeedMs float32 `protobuf:"fixed32,7,opt,name=wind_speed_ms,json=windSpeedMs,proto3" json:"wind_speed_ms,omitempty"`
	// Wind direction in degrees (0 = from North)
	WindDirectionDeg float32 `protobuf:"fixed32,8,opt,name=wind_direction_deg,json=windDirectionDeg,proto3" json:"wind_direction_deg,omitempty"`
	// Remaining flight time estimate in seconds
	RemainingFlightTimeSec uint32 `protobuf:"varint,9,opt,name=remaining_flight_time_sec,json=remainingFlightTimeSec,proto3" json:"remaining_flight_time_sec,omitempty"`
	// Motor temperatures in Celsius (4 motors)
	MotorTempsC []float32 `protobuf:"fixed32,10,rep,packed,name=motor_temps_c,json=motorTempsC,proto3" json:"motor_temps_c,omitempty"`
	// Home location (where it will return to)
	Home *HomeLocation `protobuf:"bytes,11,opt,name=home,proto3" json:"home,omitempty"`
	// Current tracking target (if in TRACK mode)
	TrackingTarget *TrackingTarget `protobuf:"bytes,12,opt,name=tracking_target,json=trackingTarget,proto3" json:"tracking_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SkydioTelemetry) Reset() {
	*x = SkydioTelemetry{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkydioTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkydioTelemetry) ProtoMessage() {}

func (x *SkydioTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkydioTelemetry.ProtoReflect.Descriptor instead.
func (*SkydioTelemetry) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{0}
}

func (x *SkydioTelemetry) GetFlightMode() FlightMode {
	if x != nil {
		return x.FlightMode
	}
	return FlightMode_FLIGHT_MODE_UNKNOWN
}

func (x *SkydioTelemetry) GetGpsFixQuality() uint32 {
	if x != nil {
		return x.GpsFixQuality
	}
	return 0
}

func (x *SkydioTelemetry) GetSatellites() uint32 {
	if x != nil {
		return x.Satellites
	}
	return 0
}

func (x *SkydioTelemetry) GetGimbal() *GimbalState {
	if x != nil {
		return x.Gimbal
	}
	return nil
}

func (x *SkydioTelemetry) GetObstacleAvoidance() *ObstacleAvoidance {
	if x != nil {
		return x.ObstacleAvoidance
	}
	return nil
}

func (x *SkydioTelemetry) GetRecording() *RecordingState {
	if x != nil {
		return x.Recording
	}
	return nil
}

func (x *SkydioTelemetry) GetWindSpeedMs() float32 {
	if x != nil {
		return x.WindSpeedMs
	}
	return 0
}

func (x *SkydioTelemetry) GetWindDirectionDeg() float32 {
	if x != nil {
		return x.WindDirectionDeg
	}
	return 0
}

func (x *SkydioTelemetry) GetRemainingFlightTimeSec() uint32 {
	if x != nil {
		return x.RemainingFlightTimeSec
	}
	return 0
}

func (x *SkydioTelemetry) GetMotorTempsC() []float32 {
	if x != nil {
		return x.MotorTempsC
	}
	return nil
}

func (x *SkydioTelemetry) GetHome() *HomeLocation {
	if x != nil {
		return x.Home
	}
	return nil
}

func (x *SkydioTelemetry) GetTrackingTarget() *TrackingTarget {
	if x != nil {
		return x.TrackingTarget
	}
	return nil
}

// GimbalState reports camera gimbal orientation.
type GimbalState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PitchDeg      float32                `protobuf:"fixed32,1,opt,name=pitch_deg,json=pitchDeg,proto3" json:"pitch_deg,omitempty"` // -90 (down) to +30 (up)
	YawDeg        float32                `protobuf:"fixed32,2,opt,name=yaw_deg,json=yawDeg,proto3" json:"yaw_deg,omitempty"`       // Relative to vehicle heading
	RollDeg       float32                `protobuf:"fixed32,3,opt,name=roll_deg,json=rollDeg,proto3" json:"roll_deg,omitempty"`    // Usually stabilized to 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GimbalState) Reset() {
	*x = GimbalState{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GimbalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GimbalState) ProtoMessage() {}

func (x *GimbalState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GimbalState.ProtoReflect.Descriptor instead.
func (*GimbalState) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{1}
}

func (x *GimbalState) GetPitchDeg() float32 {
	if x != nil {
		return x.PitchDeg
	}
	return 0
}

func (x *GimbalState) GetYawDeg() float32 {
	if x != nil {
		return x.YawDeg
	}
	return 0
}

func (x *GimbalState) GetRollDeg() float32 {
	if x != nil {
		return x.RollDeg
	}
	return 0
}

// ObstacleAvoidance reports the state of collision avoidance systems.
type ObstacleAvoidance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	FrontClear       bool                   `protobuf:"varint,2,opt,name=front_clear,json=frontClear,proto3" json:"front_clear,omitempty"`
	RearClear        bool                   `protobuf:"varint,3,opt,name=rear_clear,json=rearClear,proto3" json:"rear_clear,omitempty"`
	LeftClear        bool                   `protobuf:"varint,4,opt,name=left_clear,json=leftClear,proto3" json:"left_clear,omitempty"`
	RightClear       bool                   `protobuf:"varint,5,opt,name=right_clear,json=rightClear,proto3" json:"right_clear,omitempty"`
	AboveClear       bool                   `protobuf:"varint,6,opt,name=above_clear,json=aboveClear,proto3" json:"above_clear,omitempty"`
	BelowClear       bool                   `protobuf:"varint,7,opt,name=below_clear,json=belowClear,proto3" json:"below_clear,omitempty"`
	ClosestObstacleM float32                `protobuf:"fixed32,8,opt,name=closest_obstacle_m,json=closestObstacleM,proto3" json:"closest_obstacle_m,omitempty"` // Distance to nearest obstacle
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ObstacleAvoidance) Reset() {
	*x = ObstacleAvoidance{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObstacleAvoidance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObstacleAvoidance) ProtoMessage() {}

func (x *ObstacleAvoidance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObstacleAvoidance.ProtoReflect.Descriptor instead.
func (*ObstacleAvoidance) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{2}
}

func (x *ObstacleAvoidance) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ObstacleAvoidance) GetFrontClear() bool {
	if x != nil {
		return x.FrontClear
	}
	return false
}

func (x *ObstacleAvoidance) GetRearClear() bool {
	if x != nil {
		return x.RearClear
	}
	return false
}

func (x *ObstacleAvoidance) GetLeftClear() bool {
	if x != nil {
		return x.LeftClear
	}
	return false
}

func (x *ObstacleAvoidance) GetRightClear() bool {
	if x != nil {
		return x.RightClear
	}
	return false
}

func (x *ObstacleAvoidance) GetAboveClear() bool {
	if x != nil {
		return x.AboveClear
	}
	return false
}

func (x *ObstacleAvoidance) GetBelowClear() bool {
	if x != nil {
		return x.BelowClear
	}
	return false
}

func (x *ObstacleAvoidance) GetClosestObstacleM() float32 {
	if x != nil {
		return x.ClosestObstacleM
	}
	return 0
}

// RecordingState reports camera recording status.
type RecordingState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IsRecording          bool                   `protobuf:"varint,1,opt,name=is_recording,json=isRecording,proto3" json:"is_recording,omitempty"`
	RecordingDurationSec uint32                 `protobuf:"varint,2,opt,name=recording_duration_sec,json=recordingDurationSec,proto3" json:"recording_duration_sec,omitempty"`
	StorageRemainingMb   uint32                 `protobuf:"varint,3,opt,name=storage_remaining_mb,json=storageRemainingMb,proto3" json:"storage_remaining_mb,omitempty"`
	CurrentResolution    string                 `protobuf:"bytes,4,opt,name=current_resolution,json=currentResolution,proto3" json:"current_resolution,omitempty"` // e.g., "4K60", "1080p120"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RecordingState) Reset() {
	*x = RecordingState{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingState) ProtoMessage() {}

func (x *RecordingState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingState.ProtoReflect.Descriptor instead.
func (*RecordingState) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{3}
}

func (x *RecordingState) GetIsRecording() bool {
	if x != nil {
		return x.IsRecording
	}
	return false
}

func (x *RecordingState) GetRecordingDurationSec() uint32 {
	if x != nil {
		return x.RecordingDurationSec
	}
	return 0
}

func (x *RecordingState) GetStorageRemainingMb() uint32 {
	if x != nil {
		return x.StorageRemainingMb
	}
	return 0
}

func (x *RecordingState) GetCurrentResolution() string {
	if x != nil {
		return x.CurrentResolution
	}
	return ""
}

// HomeLocation is where the drone will return on RTH.
type HomeLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AltitudeMslM  float32                `protobuf:"fixed32,3,opt,name=altitude_msl_m,json=altitudeMslM,proto3" json:"altitude_msl_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeLocation) Reset() {
	*x = HomeLocation{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeLocation) ProtoMessage() {}

func (x *HomeLocation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeLocation.ProtoReflect.Descriptor instead.
func (*HomeLocation) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{4}
}

func (x *HomeLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *HomeLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *HomeLocation) GetAltitudeMslM() float32 {
	if x != nil {
		return x.AltitudeMslM
	}
	return 0
}

// TrackingTarget describes the current tracking subject.
type TrackingTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                   // 0.0 - 1.0 tracking confidence
	DistanceM     float32                `protobuf:"fixed32,3,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`    // Distance to target
	BearingDeg    float32                `protobuf:"fixed32,4,opt,name=bearing_deg,json=bearingDeg,proto3" json:"bearing_deg,omitempty"` // Bearing to target from drone
	TargetType    string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`   // "person", "vehicle", "boat", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingTarget) Reset() {
	*x = TrackingTarget{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingTarget) ProtoMessage() {}

func (x *TrackingTarget) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingTarget.ProtoReflect.Descriptor instead.
func (*TrackingTarget) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{5}
}

func (x *TrackingTarget) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TrackingTarget) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TrackingTarget) GetDistanceM() float32 {
	if x != nil {
		return x.DistanceM
	}
	return 0
}

func (x *TrackingTarget) GetBearingDeg() float32 {
	if x != nil {
		return x.BearingDeg
	}
	return 0
}

func (x *TrackingTarget) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

// SetFlightModeCommand changes the flight mode.
type SetFlightModeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          FlightMode             `protobuf:"varint,1,opt,name=mode,proto3,enum=skydio.FlightMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFlightModeCommand) Reset() {
	*x = SetFlightModeCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFlightModeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFlightModeCommand) ProtoMessage() {}

func (x *SetFlightModeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFlightModeCommand.ProtoReflect.Descriptor instead.
func (*SetFlightModeCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{6}
}

func (x *SetFlightModeCommand) GetMode() FlightMode {
	if x != nil {
		return x.Mode
	}
	return FlightMode_FLIGHT_MODE_UNKNOWN
}

// SetGimbalCommand adjusts camera gimbal orientation.
type SetGimbalCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PitchDeg       float32                `protobuf:"fixed32,1,opt,name=pitch_deg,json=pitchDeg,proto3" json:"pitch_deg,omitempty"` // -90 to +30
	YawDeg         float32                `protobuf:"fixed32,2,opt,name=yaw_deg,json=yawDeg,proto3" json:"yaw_deg,omitempty"`       // Relative to heading, or absolute if use_absolute_yaw is true
	UseAbsoluteYaw bool                   `protobuf:"varint,3,opt,name=use_absolute_yaw,json=useAbsoluteYaw,proto3" json:"use_absolute_yaw,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetGimbalCommand) Reset() {
	*x = SetGimbalCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGimbalCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGimbalCommand) ProtoMessage() {}

func (x *SetGimbalCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGimbalCommand.ProtoReflect.Descriptor instead.
func (*SetGimbalCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{7}
}

func (x *SetGimbalCommand) GetPitchDeg() float32 {
	if x != nil {
		return x.PitchDeg
	}
	return 0
}

func (x *SetGimbalCommand) GetYawDeg() float32 {
	if x != nil {
		return x.YawDeg
	}
	return 0
}

func (x *SetGimbalCommand) GetUseAbsoluteYaw() bool {
	if x != nil {
		return x.UseAbsoluteYaw
	}
	return false
}

// StartRecordingCommand begins video recording.
type StartRecordingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolution    string                 `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"` // "4K60", "4K30", "1080p120", "1080p60"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecordingCommand) Reset() {
	*x = StartRecordingCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecordingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordingCommand) ProtoMessage() {}

func (x *StartRecordingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordingCommand.ProtoReflect.Descriptor instead.
func (*StartRecordingCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{8}
}

func (x *StartRecordingCommand) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

// StopRecordingCommand stops video recording.
type StopRecordingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingCommand) Reset() {
	*x = StopRecordingCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingCommand) ProtoMessage() {}

func (x *StopRecordingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingCommand.ProtoReflect.Descriptor instead.
func (*StopRecordingCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{9}
}

// TakePhotoCommand captures a still image.
type TakePhotoCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakePhotoCommand) Reset() {
	*x = TakePhotoCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakePhotoCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakePhotoCommand) ProtoMessage() {}

func (x *TakePhotoCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakePhotoCommand.ProtoReflect.Descriptor instead.
func (*TakePhotoCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{10}
}

// OrbitCommand starts orbiting a point of interest.
type OrbitCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CenterLat     float64                `protobuf:"fixed64,1,opt,name=center_lat,json=centerLat,proto3" json:"center_lat,omitempty"`
	CenterLng     float64                `protobuf:"fixed64,2,opt,name=center_lng,json=centerLng,proto3" json:"center_lng,omitempty"`
	RadiusM       float32                `protobuf:"fixed32,3,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	AltitudeM     float32                `protobuf:"fixed32,4,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"` // Altitude above ground
	SpeedMs       float32                `protobuf:"fixed32,5,opt,name=speed_ms,json=speedMs,proto3" json:"speed_ms,omitempty"`       // Orbit speed
	Clockwise     bool                   `protobuf:"varint,6,opt,name=clockwise,proto3" json:"clockwise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrbitCommand) Reset() {
	*x = OrbitCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrbitCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitCommand) ProtoMessage() {}

func (x *OrbitCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitCommand.ProtoReflect.Descriptor instead.
func (*OrbitCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{11}
}

func (x *OrbitCommand) GetCenterLat() float64 {
	if x != nil {
		return x.CenterLat
	}
	return 0
}

func (x *OrbitCommand) GetCenterLng() float64 {
	if x != nil {
		return x.CenterLng
	}
	return 0
}

func (x *OrbitCommand) GetRadiusM() float32 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

func (x *OrbitCommand) GetAltitudeM() float32 {
	if x != nil {
		return x.AltitudeM
	}
	return 0
}

func (x *OrbitCommand) GetSpeedMs() float32 {
	if x != nil {
		return x.SpeedMs
	}
	return 0
}

func (x *OrbitCommand) GetClockwise() bool {
	if x != nil {
		return x.Clockwise
	}
	return false
}

// TrackCommand starts tracking a subject.
type TrackCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Screen coordinates of target to track (normalized 0-1)
	ScreenX       float32 `protobuf:"fixed32,1,opt,name=screen_x,json=screenX,proto3" json:"screen_x,omitempty"`
	ScreenY       float32 `protobuf:"fixed32,2,opt,name=screen_y,json=screenY,proto3" json:"screen_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackCommand) Reset() {
	*x = TrackCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackCommand) ProtoMessage() {}

func (x *TrackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackCommand.ProtoReflect.Descriptor instead.
func (*TrackCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{12}
}

func (x *TrackCommand) GetScreenX() float32 {
	if x != nil {
		return x.ScreenX
	}
	return 0
}

func (x *TrackCommand) GetScreenY() float32 {
	if x != nil {
		return x.ScreenY
	}
	return 0
}

// StopTrackingCommand stops autonomous tracking.
type StopTrackingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTrackingCommand) Reset() {
	*x = StopTrackingCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTrackingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTrackingCommand) ProtoMessage() {}

func (x *StopTrackingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTrackingCommand.ProtoReflect.Descriptor instead.
func (*StopTrackingCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{13}
}

// SetHomeCommand updates the home location.
type SetHomeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHomeCommand) Reset() {
	*x = SetHomeCommand{}
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHomeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHomeCommand) ProtoMessage() {}

func (x *SetHomeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_extensions_skydio_skydio_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHomeCommand.ProtoReflect.Descriptor instead.
func (*SetHomeCommand) Descriptor() ([]byte, []int) {
	return file_internal_extensions_skydio_skydio_proto_rawDescGZIP(), []int{14}
}

func (x *SetHomeCommand) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SetHomeCommand) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_internal_extensions_skydio_skydio_proto protoreflect.FileDescriptor

const file_internal_extensions_skydio_skydio_proto_rawDesc = "" +
	"\n" +
	"'internal/extensions/skydio/skydio.proto\x12\x06skydio\"\xd7\x04\n" +
	"\x0fSkydioTelemetry\x123\n" +
	"\vflight_mode\x18\x01 \x01(\x0e2\x12.skydio.FlightModeR\n" +
	"flightMode\x12&\n" +
	"\x0fgps_fix_quality\x18\x02 \x01(\rR\rgpsFixQuality\x12\x1e\n" +
	"\n" +
	"satellites\x18\x03 \x01(\rR\n" +
	"satellites\x12+\n" +
	"\x06gimbal\x18\x04 \x01(\v2\x13.skydio.GimbalStateR\x06gimbal\x12H\n" +
	"\x12obstacle_avoidance\x18\x05 \x01(\v2\x19.skydio.ObstacleAvoidanceR\x11obstacleAvoidance\x124\n" +
	"\trecording\x18\x06 \x01(\v2\x16.skydio.RecordingStateR\trecording\x12\"\n" +
	"\rwind_speed_ms\x18\a \x01(\x02R\vwindSpeedMs\x12,\n" +
	"\x12wind_direction_deg\x18\b \x01(\x02R\x10windDirectionDeg\x129\n" +
	"\x19remaining_flight_time_sec\x18\t \x01(\rR\x16remainingFlightTimeSec\x12\"\n" +
	"\rmotor_temps_c\x18\n" +
	" \x03(\x02R\vmotorTempsC\x12(\n" +
	"\x04home\x18\v \x01(\v2\x14.skydio.HomeLocationR\x04home\x12?\n" +
	"\x0ftracking_target\x18\f \x01(\v2\x16.skydio.TrackingTargetR\x0etrackingTarget\"^\n" +
	"\vGimbalState\x12\x1b\n" +
	"\tpitch_deg\x18\x01 \x01(\x02R\bpitchDeg\x12\x17\n" +
	"\ayaw_deg\x18\x02 \x01(\x02R\x06yawDeg\x12\x19\n" +
	"\broll_deg\x18\x03 \x01(\x02R\arollDeg\"\x9d\x02\n" +
	"\x11ObstacleAvoidance\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vfront_clear\x18\x02 \x01(\bR\n" +
	"frontClear\x12\x1d\n" +
	"\n" +
	"rear_clear\x18\x03 \x01(\bR\trearClear\x12\x1d\n" +
	"\n" +
	"left_clear\x18\x04 \x01(\bR\tleftClear\x12\x1f\n" +
	"\vright_clear\x18\x05 \x01(\bR\n" +
	"rightClear\x12\x1f\n" +
	"\vabove_clear\x18\x06 \x01(\bR\n" +
	"aboveClear\x12\x1f\n" +
	"\vbelow_clear\x18\a \x01(\bR\n" +
	"belowClear\x12,\n" +
	"\x12closest_obstacle_m\x18\b \x01(\x02R\x10closestObstacleM\"\xca\x01\n" +
	"\x0eRecordingState\x12!\n" +
	"\fis_recording\x18\x01 \x01(\bR\visRecording\x124\n" +
	"\x16recording_duration_sec\x18\x02 \x01(\rR\x14recordingDurationSec\x120\n" +
	"\x14storage_remaining_mb\x18\x03 \x01(\rR\x12storageRemainingMb\x12-\n" +
	"\x12current_resolution\x18\x04 \x01(\tR\x11currentResolution\"n\n" +
	"\fHomeLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12$\n" +
	"\x0ealtitude_msl_m\x18\x03 \x01(\x02R\faltitudeMslM\"\xa9\x01\n" +
	"\x0eTrackingTarget\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"distance_m\x18\x03 \x01(\x02R\tdistanceM\x12\x1f\n" +
	"\vbearing_deg\x18\x04 \x01(\x02R\n" +
	"bearingDeg\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\">\n" +
	"\x14SetFlightModeCommand\x12&\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x12.skydio.FlightModeR\x04mode\"r\n" +
	"\x10SetGimbalCommand\x12\x1b\n" +
	"\tpitch_deg\x18\x01 \x01(\x02R\bpitchDeg\x12\x17\n" +
	"\ayaw_deg\x18\x02 \x01(\x02R\x06yawDeg\x12(\n" +
	"\x10use_absolute_yaw\x18\x03 \x01(\bR\x0euseAbsoluteYaw\"7\n" +
	"\x15StartRecordingCommand\x12\x1e\n" +
	"\n" +
	"resolution\x18\x01 \x01(\tR\n" +
	"resolution\"\x16\n" +
	"\x14StopRecordingCommand\"\x12\n" +
	"\x10TakePhotoCommand\"\xbf\x01\n" +
	"\fOrbitCommand\x12\x1d\n" +
	"\n" +
	"center_lat\x18\x01 \x01(\x01R\tcenterLat\x12\x1d\n" +
	"\n" +
	"center_lng\x18\x02 \x01(\x01R\tcenterLng\x12\x19\n" +
	"\bradius_m\x18\x03 \x01(\x02R\aradiusM\x12\x1d\n" +
	"\n" +
	"altitude_m\x18\x04 \x01(\x02R\taltitudeM\x12\x19\n" +
	"\bspeed_ms\x18\x05 \x01(\x02R\aspeedMs\x12\x1c\n" +
	"\tclockwise\x18\x06 \x01(\bR\tclockwise\"D\n" +
	"\fTrackCommand\x12\x19\n" +
	"\bscreen_x\x18\x01 \x01(\x02R\ascreenX\x12\x19\n" +
	"\bscreen_y\x18\x02 \x01(\x02R\ascreenY\"\x15\n" +
	"\x13StopTrackingCommand\"J\n" +
	"\x0eSetHomeCommand\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude*\x9e\x02\n" +
	"\n" +
	"FlightMode\x12\x17\n" +
	"\x13FLIGHT_MODE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10FLIGHT_MODE_IDLE\x10\x01\x12\x15\n" +
	"\x11FLIGHT_MODE_HOVER\x10\x02\x12\x16\n" +
	"\x12FLIGHT_MODE_MANUAL\x10\x03\x12\x18\n" +
	"\x14FLIGHT_MODE_WAYPOINT\x10\x04\x12\x15\n" +
	"\x11FLIGHT_MODE_ORBIT\x10\x05\x12\x15\n" +
	"\x11FLIGHT_MODE_TRACK\x10\x06\x12\x19\n" +
	"\x15FLIGHT_MODE_CABLE_CAM\x10\a\x12\x1b\n" +
	"\x17FLIGHT_MODE_RETURN_HOME\x10\b\x12\x17\n" +
	"\x13FLIGHT_MODE_LANDING\x10\t\x12\x19\n" +
	"\x15FLIGHT_MODE_EMERGENCY\x10\n" +
	"B?Z=github.com/EthanMBoos/tower-server/internal/extensions/skydiob\x06proto3"

var (
	file_internal_extensions_skydio_skydio_proto_rawDescOnce sync.Once
	file_internal_extensions_skydio_skydio_proto_rawDescData []byte
)

func file_internal_extensions_skydio_skydio_proto_rawDescGZIP() []byte {
	file_internal_extensions_skydio_skydio_proto_rawDescOnce.Do(func() {
		file_internal_extensions_skydio_skydio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_extensions_skydio_skydio_proto_rawDesc), len(file_internal_extensions_skydio_skydio_proto_rawDesc)))
	})
	return file_internal_extensions_skydio_skydio_proto_rawDescData
}

var file_internal_extensions_skydio_skydio_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_extensions_skydio_skydio_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_extensions_skydio_skydio_proto_goTypes = []any{
	(FlightMode)(0),               // 0: skydio.FlightMode
	(*SkydioTelemetry)(nil),       // 1: skydio.SkydioTelemetry
	(*GimbalState)(nil),           // 2: skydio.GimbalState
	(*ObstacleAvoidance)(nil),     // 3: skydio.ObstacleAvoidance
	(*RecordingState)(nil),        // 4: skydio.RecordingState
	(*HomeLocation)(nil),          // 5: skydio.HomeLocation
	(*TrackingTarget)(nil),        // 6: skydio.TrackingTarget
	(*SetFlightModeCommand)(nil),  // 7: skydio.SetFlightModeCommand
	(*SetGimbalCommand)(nil),      // 8: skydio.SetGimbalCommand
	(*StartRecordingCommand)(nil), // 9: skydio.StartRecordingCommand
	(*StopRecordingCommand)(nil),  // 10: skydio.StopRecordingCommand
	(*TakePhotoCommand)(nil),      // 11: skydio.TakePhotoCommand
	(*OrbitCommand)(nil),          // 12: skydio.OrbitCommand
	(*TrackCommand)(nil),          // 13: skydio.TrackCommand
	(*StopTrackingCommand)(nil),   // 14: skydio.StopTrackingCommand
	(*SetHomeCommand)(nil),        // 15: skydio.SetHomeCommand
}
var file_internal_extensions_skydio_skydio_proto_depIdxs = []int32{
	0, // 0: skydio.SkydioTelemetry.flight_mode:type_name -> skydio.FlightMode
	2, // 1: skydio.SkydioTelemetry.gimbal:type_name -> skydio.GimbalState
	3, // 2: skydio.SkydioTelemetry.obstacle_avoidance:type_name -> skydio.ObstacleAvoidance
	4, // 3: skydio.SkydioTelemetry.recording:type_name -> skydio.RecordingState
	5, // 4: skydio.SkydioTelemetry.home:type_name -> skydio.HomeLocation
	6, // 5: skydio.SkydioTelemetry.tracking_target:type_name -> skydio.TrackingTarget
	0, // 6: skydio.SetFlightModeCommand.mode:type_name -> skydio.FlightMode
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_extensions_skydio_skydio_proto_init() }
func file_internal_extensions_skydio_skydio_proto_init() {
	if File_internal_extensions_skydio_skydio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_extensions_skydio_skydio_proto_rawDesc), len(file_internal_extensions_skydio_skydio_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_extensions_skydio_skydio_proto_goTypes,
		DependencyIndexes: file_internal_extensions_skydio_skydio_proto_depIdxs,
		EnumInfos:         file_internal_extensions_skydio_skydio_proto_enumTypes,
		MessageInfos:      file_internal_extensions_skydio_skydio_proto_msgTypes,
	}.Build()
	File_internal_extensions_skydio_skydio_proto = out.File
	file_internal_extensions_skydio_skydio_proto_goTypes = nil
	file_internal_extensions_skydio_skydio_proto_depIdxs = nil
}
